My Application: Computer Graphics/irrKlang/plugins/ikpMP3/decoder/bits.c File Reference
bits.c File Reference
#include "internal.h"
Macros
#define GET_DATA(v, table, i, wrap, size)
Functions
void init_get_bits (GetBitContext *s, const uint8_t *buffer, int bit_size)
init GetBitContext.
unsigned int show_bits (const GetBitContext *s, int n)
void skip_bits (GetBitContext *s, int n)
unsigned int get_bits (GetBitContext *s, int n)
int get_bits_count (const GetBitContext *s)
static int alloc_table (VLC *vlc, int size)
static int build_table (VLC *vlc, int table_nb_bits, int nb_codes, const void *bits, int bits_wrap, int bits_size, const void *codes, int codes_wrap, int codes_size, uint32_t code_prefix, int n_prefix)
int init_vlc (VLC *vlc, int nb_bits, int nb_codes, const void *bits, int bits_wrap, int bits_size, const void *codes, int codes_wrap, int codes_size)
void free_vlc (VLC *vlc)
int get_vlc (GetBitContext *s, const VLC *vlc)
Macro Definition Documentation
#define GET_DATA (v, table, i, wrap, size)
Value:
{\
    const uint8_t *ptr = (const uint8_t *)table + i * wrap;\
    switch(size) {\
    case 1:\
        v = *(const uint8_t *)ptr;\
        break;\
    case 2:\
        v = *(const uint16_t *)ptr;\
        break;\
    default:\
        v = *(const uint32_t *)ptr;\
        break;\
    }\
}
Definition at line 79 of file bits.c.
Referenced by build_table().
Function Documentation
static int alloc_table (VLC * vlc, int size) static
Definition at line 96 of file bits.c.
References VLC::bits, VLC::table, VLC::table_allocated, VLC::table_size, and VLC_TYPE.
Referenced by build_table(), and mp_decode_layer2().
static int build_table (VLC * vlc, int table_nb_bits, int nb_codes, const void * bits, int bits_wrap, int bits_size, const void * codes, int codes_wrap, int codes_size, uint32_t code_prefix, int n_prefix) static
Definition at line 111 of file bits.c.
References alloc_table(), GET_DATA, VLC::table, and VLC_TYPE.
Referenced by init_vlc().
void free_vlc (VLC * vlc)
Definition at line 248 of file bits.c.
References VLC::table.
unsigned int get_bits (GetBitContext * s, int n)
Definition at line 63 of file bits.c.
References show_bits(), and skip_bits().
Referenced by get_bitsz(), huffman_decode(), mp_decode_frame(), mp_decode_layer1(), mp_decode_layer2(), and mp_decode_layer3().
int get_bits_count (const GetBitContext * s)
Definition at line 70 of file bits.c.
References GetBitContext::index.
Referenced by huffman_decode(), mp_decode_layer3(), and seek_to_maindata().
int get_vlc (GetBitContext * s, const VLC * vlc)
Definition at line 253 of file bits.c.
References VLC::bits, show_bits(), skip_bits(), and VLC::table.
Referenced by huffman_decode().
void init_get_bits (GetBitContext * s, const uint8_t * buffer, int bit_size)
init GetBitContext.
Parameters
buffer bitstream buffer
bit_size the size of the buffer in bits
Definition at line 30 of file bits.c.
References GetBitContext::buffer, GetBitContext::index, and GetBitContext::size_in_bits.
Referenced by mp_decode_frame(), and seek_to_maindata().
int init_vlc (VLC * vlc, int nb_bits, int nb_codes, const void * bits, int bits_wrap, int bits_size, const void * codes, int codes_wrap, int codes_size)
Definition at line 225 of file bits.c.
References VLC::bits, build_table(), VLC::table, VLC::table_allocated, and VLC::table_size.
Referenced by mpaudec_init().
unsigned int show_bits (const GetBitContext * s, int n)
Definition at line 38 of file bits.c.
References GetBitContext::buffer, GetBitContext::index, and GetBitContext::size_in_bits.
Referenced by get_bits(), and get_vlc().
void skip_bits (GetBitContext * s, int n)
Definition at line 58 of file bits.c.
References GetBitContext::index.
Referenced by get_bits(), get_vlc(), and mp_decode_layer3().