My Application: Player Class Reference
Player Class Reference
Class for Player (Inheriting from GameChar) /*.
#include <Player.h>
Public Member Functions
Player ()
Player (Vector3 pos)
~Player ()
void movementUpdate (Camera3 &cam, double dt, vector< GameObject * > collisionVec)
void movementUpdate (Camera3 &cam, double dt, vector< GameObject * > collisionVec, PMAP map)
bool haveAcceptedCheck (Quest *q)
bool receiveQuest (Quest *q)
bool receiveQuest (GameChar &x)
void taskComplete (int questIndex, int index)
bool questCompleted (int index)
void setQuest ()
bool completedMainQuest ()
string getOxygenString ()
Public Member Functions inherited from GameChar
~GameChar ()
vector< string > ReadFromTxt (string link)
void chat_update (Vector3 player_pos)
bool isDead ()
smaller getHealth ()
string getHealthString ()
bool recieveHealthDamage (const int &damage)
void regainHealth (const int &healAMT=1)
void assignQuest (Quest *q)
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Data Fields
float f_walkSpeed
float f_sprintSpeed
float f_jumpDebounceTimer
float f_initialJumpSpeed
float f_jumpSpeed
float f_gravity
bool b_jumpDebounce
bool b_jumpUp
float groundLevel
smaller oxygen
Data Fields inherited from GameChar
int dialogue_index
bool b_indexDebounce
bool isPressed
vector< string > vec_dialog
bool b_dialogueEnd
int chat_boundary
Quest * quest
Data Fields inherited from GameObject
string name
int boundary
Vector3 pos
float viewAngle
Static Public Attributes
static vector< Quest * > questList
Static Public Attributes inherited from GameChar
static size_t GC_count = 0
Additional Inherited Members
Protected Member Functions inherited from GameChar
GameChar ()
GameChar (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0), smaller init_Health=0)
Protected Member Functions inherited from GameObject
GameObject ()
GameObject (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
Detailed Description
Class for Player (Inheriting from GameChar) /*.
Class Player:
Definition at line 34 of file Player.h.
Constructor & Destructor Documentation
Player::Player ()
Definition at line 8 of file Player.cpp.
References b_jumpDebounce, b_jumpUp, GameObject::boundary, f_gravity, f_initialJumpSpeed, f_jumpDebounceTimer, f_jumpSpeed, f_sprintSpeed, f_walkSpeed, groundLevel, GameObject::name, oxygen, GameObject::pos, and GameObject::viewAngle.
Player::Player (Vector3 pos)
Definition at line 26 of file Player.cpp.
References b_jumpDebounce, b_jumpUp, GameObject::boundary, f_gravity, f_initialJumpSpeed, f_jumpDebounceTimer, f_jumpSpeed, f_sprintSpeed, f_walkSpeed, groundLevel, GameObject::name, GameObject::pos, and GameObject::viewAngle.
Player::~Player ()
Definition at line 43 of file Player.cpp.
Member Function Documentation
bool Player::completedMainQuest ()
Definition at line 402 of file Player.cpp.
References questCompleted().
Referenced by Sp2_Scene1::Update().
string Player::getOxygenString ()
Definition at line 414 of file Player.cpp.
References oxygen.
Referenced by Sp2_Scene3::RenderSuit().
bool Player::haveAcceptedCheck (Quest * q)
Definition at line 355 of file Player.cpp.
References questList.
Referenced by receiveQuest().
void Player::movementUpdate (Camera3 & cam, double dt, vector< GameObject * > collisionVec)
Definition at line 48 of file Player.cpp.
References b_jumpDebounce, b_jumpUp, GameObject::boundary, Camera3::boundaryX, Camera3::boundaryZ, Camera3::cameraRotationY, collision(), Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), f_gravity, f_initialJumpSpeed, f_jumpDebounceTimer, f_jumpSpeed, f_sprintSpeed, f_walkSpeed, groundLevel, Application::IsKeyPressed(), Vector3::Normalize(), Vector3::Normalized(), GameObject::pos, Camera3::position, Camera3::right, Camera3::target, Camera3::up, Camera3::updateRotation(), Camera3::view, GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Sp2_Scene1::Update(), Sp2_Scene3::Update(), and Sp2_SpaceRace::Update().
void Player::movementUpdate (Camera3 & cam, double dt, vector< GameObject * > collisionVec, PMAP map)
Definition at line 190 of file Player.cpp.
References b_jumpDebounce, b_jumpUp, GameObject::boundary, Camera3::boundaryX, Camera3::boundaryZ, Camera3::cameraRotationY, collision(), Vector3::Cross(), sMap::data, Camera3::defaultUp, Math::DegreeToRadian(), f_gravity, f_initialJumpSpeed, f_jumpDebounceTimer, f_jumpSpeed, f_sprintSpeed, f_walkSpeed, groundLevel, Application::IsKeyPressed(), Vector3::Normalize(), Vector3::Normalized(), GameObject::pos, Camera3::position, Camera3::right, Camera3::target, Camera3::up, Camera3::updateRotation(), vectorToIndex(), Camera3::view, GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
bool Player::questCompleted (int index)
Definition at line 393 of file Player.cpp.
References questList.
Referenced by completedMainQuest().
bool Player::receiveQuest (Quest * q)
Definition at line 367 of file Player.cpp.
References haveAcceptedCheck(), and questList.
Referenced by receiveQuest().
bool Player::receiveQuest (GameChar & x)
Definition at line 383 of file Player.cpp.
References GameChar::quest, and receiveQuest().
void Player::setQuest ()
Definition at line 176 of file Player.cpp.
References questList.
Referenced by Sp2_Scene1::Init().
void Player::taskComplete (int questIndex, int index)
Definition at line 388 of file Player.cpp.
References questList.
Field Documentation
bool Player::b_jumpDebounce
Definition at line 48 of file Player.h.
Referenced by movementUpdate(), and Player().
bool Player::b_jumpUp
Definition at line 49 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_gravity
Definition at line 47 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_initialJumpSpeed
Definition at line 45 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_jumpDebounceTimer
Definition at line 44 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_jumpSpeed
Definition at line 46 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_sprintSpeed
Definition at line 43 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::f_walkSpeed
Definition at line 42 of file Player.h.
Referenced by movementUpdate(), and Player().
float Player::groundLevel
Definition at line 50 of file Player.h.
Referenced by movementUpdate(), and Player().
smaller Player::oxygen
Definition at line 51 of file Player.h.
Referenced by getOxygenString(), Sp2_Scene3::Init(), Player(), and Sp2_Scene3::Update().
vector< Quest * > Player::questList static
Definition at line 53 of file Player.h.
Referenced by haveAcceptedCheck(), questCompleted(), receiveQuest(), Application::Run(), setQuest(), taskComplete(), Sp2_Scene1::Update(), Sp2_SpaceRace::Update(), and Sp2_Scene1::~Sp2_Scene1().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Player.h
Computer Graphics/Source/Player.cpp