My Application: CameraTPS Class Reference
CameraTPS Class Reference
Class for the third type of camera (Inheriting from Camera) /*.
#include <CameraTPS.h>
Public Member Functions
CameraTPS ()
~CameraTPS ()
virtual void Init (const Vector3 &pos, const Vector3 &up, GameObject *targetObj)
void tpsUpdateRotation (float speed)
void tpsUpdateVec (double dt)
Public Member Functions inherited from Camera
Camera ()
Default constructor.
~Camera ()
Destructor.
void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Initialize camera.
void Reset ()
Reset the camera settings.
void Update (double dt)
To be called every frame. Camera will get user inputs and update its position and orientation.
Data Fields
float cameraRotationX
float cameraRotationY
Vector3 defaultOffset
Vector3 defaultUp
Vector3 right
Vector3 view
GameObject * targetObj
bool b_cameraLock
bool b_cameraLockDebounce
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Detailed Description
Class for the third type of camera (Inheriting from Camera) /*.
Class CameraTPS:
Definition at line 26 of file CameraTPS.h.
Constructor & Destructor Documentation
CameraTPS::CameraTPS ()
Definition at line 6 of file CameraTPS.cpp.
CameraTPS::~CameraTPS ()
Definition at line 10 of file CameraTPS.cpp.
Member Function Documentation
void CameraTPS::Init (const Vector3 & pos, const Vector3 & up, GameObject * targetObj) virtual
Definition at line 14 of file CameraTPS.cpp.
References b_cameraLock, b_cameraLockDebounce, cameraRotationX, cameraRotationY, Vector3::Cross(), defaultOffset, defaultUp, Vector3::Normalize(), Vector3::Normalized(), GameObject::pos, Camera::position, right, Camera::target, targetObj, view, and Vector3::y.
Referenced by Sp2_SpaceRace::Init().
void CameraTPS::tpsUpdateRotation (float speed)
Definition at line 35 of file CameraTPS.cpp.
References cameraRotationX, cameraRotationY, defaultOffset, Math::DegreeToRadian(), m_window, Camera::position, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by tpsUpdateVec().
void CameraTPS::tpsUpdateVec (double dt)
Definition at line 70 of file CameraTPS.cpp.
References b_cameraLock, b_cameraLockDebounce, cameraRotationY, Vector3::Cross(), defaultOffset, defaultUp, Math::DegreeToRadian(), Application::IsKeyPressed(), Vector3::Normalize(), Vector3::Normalized(), GameObject::pos, Camera::position, right, Camera::target, targetObj, tpsUpdateRotation(), Camera::up, view, GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Sp2_SpaceRace::Update().
Field Documentation
bool CameraTPS::b_cameraLock
Definition at line 37 of file CameraTPS.h.
Referenced by Init(), tpsUpdateVec(), and Sp2_SpaceRace::Update().
bool CameraTPS::b_cameraLockDebounce
Definition at line 38 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateVec().
float CameraTPS::cameraRotationX
Definition at line 29 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateRotation().
float CameraTPS::cameraRotationY
Definition at line 30 of file CameraTPS.h.
Referenced by Init(), tpsUpdateRotation(), and tpsUpdateVec().
Vector3 CameraTPS::defaultOffset
Definition at line 31 of file CameraTPS.h.
Referenced by Init(), tpsUpdateRotation(), and tpsUpdateVec().
Vector3 CameraTPS::defaultUp
Definition at line 33 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateVec().
Vector3 CameraTPS::right
Definition at line 34 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateVec().
GameObject* CameraTPS::targetObj
Definition at line 36 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateVec().
Vector3 CameraTPS::view
Definition at line 35 of file CameraTPS.h.
Referenced by Init(), and tpsUpdateVec().
The documentation for this class was generated from the following files:
Computer Graphics/Source/CameraTPS.h
Computer Graphics/Source/CameraTPS.cpp