My Application: Music Class Reference
Music Class Reference
Class for the overall music in the game /*.
#include <Music.h>
Public Member Functions
Music ()
~Music ()
void Init ()
vector< string > readFromText (string link)
void OpeningMusic (int index, bool loop)
Data Fields
irrklang::ISoundEngine * engine
vector< irrklang::ISoundSource * > sound
vector< string > musicVec
Detailed Description
Class for the overall music in the game /*.
Class Music:
Definition at line 35 of file Music.h.
Constructor & Destructor Documentation
Music::Music ()
Definition at line 3 of file Music.cpp.
Music::~Music ()
Definition at line 7 of file Music.cpp.
Member Function Documentation
void Music::Init ()
Definition at line 36 of file Music.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), irrklang::createIrrKlangDevice(), engine, musicVec, readFromText(), and sound.
Referenced by Application::Run().
void Music::OpeningMusic (int index, bool loop)
Definition at line 52 of file Music.cpp.
References engine, irrklang::ISoundEngine::play2D(), and sound.
Referenced by Application::playSound().
vector< string > Music::readFromText (string link)
Definition at line 12 of file Music.cpp.
Referenced by Init().
Field Documentation
irrklang::ISoundEngine* Music::engine
Definition at line 45 of file Music.h.
Referenced by Init(), and OpeningMusic().
vector<string> Music::musicVec
Definition at line 47 of file Music.h.
Referenced by Init().
vector<irrklang::ISoundSource*> Music::sound
Definition at line 46 of file Music.h.
Referenced by Init(), and OpeningMusic().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Music.h
Computer Graphics/Source/Music.cpp