My Application: LoadingScene Class Reference
LoadingScene Class Reference
Class for LoadingScene (Inheriting from Scene) /*.
#include <LoadingScene.h>
Public Types
enum GEOMETRY_TYPE { GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, NUM_GEOMETRY }
enum UNIFORM_TYPE {
U_MVP, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Public Member Functions
LoadingScene ()
~LoadingScene ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
unsigned m_parameters [U_TOTAL]
Camera3 camera
CameraTPS camera2
int screenWidth
int screenHeight
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSpaceVehicles (Camera3 camera)
void Renderfps ()
void Rendertps ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderMeshOnScreen (Mesh *mesh, Vector3 translate=Vector3(0, 0, 0), Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
Private Attributes
unsigned m_vertexArrayID
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_indexBuffer [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
MS viewStack2
float f_rotateCube
Mesh * meshList [NUM_GEOMETRY]
Light light [1]
Detailed Description
Class for LoadingScene (Inheriting from Scene) /*.
Class LoadingScene:
Definition at line 47 of file LoadingScene.h.
Member Enumeration Documentation
enum LoadingScene::GEOMETRY_TYPE
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
NUM_GEOMETRY
Definition at line 58 of file LoadingScene.h.
enum LoadingScene::UNIFORM_TYPE
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 71 of file LoadingScene.h.
Constructor & Destructor Documentation
LoadingScene::LoadingScene ()
Definition at line 16 of file LoadingScene.cpp.
LoadingScene::~LoadingScene ()
Definition at line 20 of file LoadingScene.cpp.
Member Function Documentation
void LoadingScene::Exit () virtual
Implements Scene.
Definition at line 368 of file LoadingScene.cpp.
References m_programID, and m_vertexArrayID.
void LoadingScene::Init () virtual
Implements Scene.
Definition at line 24 of file LoadingScene.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateQuad(), GEO_AXES, GEO_QUAD, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, LoadShaders(), LoadTGA(), m_colorBuffer, m_indexBuffer, m_parameters, m_programID, m_vertexArrayID, m_vertexBuffer, m_window, meshList, NUM_GEOMETRY, Light::position, Light::power, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void LoadingScene::Render () virtual
Implements Scene.
Definition at line 335 of file LoadingScene.cpp.
References camera, MS::LoadIdentity(), MS::LoadMatrix(), MS::LookAt(), Camera3::position, projectionStack, Renderfps(), Mtx44::SetToPerspective(), Camera3::target, Camera3::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void LoadingScene::Renderfps () private
Definition at line 312 of file LoadingScene.cpp.
References GEO_LIGHTBALL, GEO_QUAD, light, m_parameters, meshList, modelStack, MS::PopMatrix(), Light::position, MS::PushMatrix(), RenderMesh(), RenderMeshOnScreen(), MS::Top(), MS::Translate(), U_LIGHT0_POSITION, viewStack, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void LoadingScene::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 169 of file LoadingScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Renderfps(), and RenderMeshOnScreen().
void LoadingScene::RenderMeshOnScreen (Mesh * mesh, Vector3 translate = Vector3(0, 0, 0), Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 287 of file LoadingScene.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void LoadingScene::RenderSpaceVehicles (Camera3 camera) private
void LoadingScene::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 213 of file LoadingScene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void LoadingScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 242 of file LoadingScene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void LoadingScene::Rendertps () private
Definition at line 330 of file LoadingScene.cpp.
void LoadingScene::Update (double dt) virtual
Implements Scene.
Definition at line 142 of file LoadingScene.cpp.
References Application::IsKeyPressed().
Field Documentation
Camera3 LoadingScene::camera
Definition at line 102 of file LoadingScene.h.
Referenced by Init(), and Render().
CameraTPS LoadingScene::camera2
Definition at line 103 of file LoadingScene.h.
float LoadingScene::f_rotateCube private
Definition at line 116 of file LoadingScene.h.
Light LoadingScene::light[1] private
Definition at line 118 of file LoadingScene.h.
Referenced by Init(), and Renderfps().
unsigned LoadingScene::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 111 of file LoadingScene.h.
Referenced by Init().
unsigned LoadingScene::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 113 of file LoadingScene.h.
Referenced by Init().
unsigned LoadingScene::m_parameters[U_TOTAL]
Definition at line 100 of file LoadingScene.h.
Referenced by Init(), Renderfps(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned LoadingScene::m_programID private
Definition at line 112 of file LoadingScene.h.
Referenced by Exit(), and Init().
unsigned LoadingScene::m_vertexArrayID private
Definition at line 109 of file LoadingScene.h.
Referenced by Exit(), and Init().
unsigned LoadingScene::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 110 of file LoadingScene.h.
Referenced by Init().
Mesh* LoadingScene::meshList[NUM_GEOMETRY] private
Definition at line 117 of file LoadingScene.h.
Referenced by Init(), and Renderfps().
MS LoadingScene::modelStack private
Definition at line 115 of file LoadingScene.h.
Referenced by Renderfps(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
MS LoadingScene::projectionStack private
Definition at line 115 of file LoadingScene.h.
Referenced by Render(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
int LoadingScene::screenHeight
Definition at line 105 of file LoadingScene.h.
Referenced by Init().
int LoadingScene::screenWidth
Definition at line 105 of file LoadingScene.h.
Referenced by Init().
MS LoadingScene::viewStack private
Definition at line 115 of file LoadingScene.h.
Referenced by Render(), Renderfps(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
MS LoadingScene::viewStack2 private
Definition at line 115 of file LoadingScene.h.
The documentation for this class was generated from the following files:
Computer Graphics/Source/LoadingScene.h
Computer Graphics/Source/LoadingScene.cpp