My Application: Sp2_SpaceRace Class Reference
Sp2_SpaceRace Class Reference
Class for the Space Race Scene inheriting from Scene /*.
#include <Sp2_SpaceRace.h>
Public Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, GEO_LEFT,
GEO_RIGHT, GEO_TOP, GEO_BOTTOM, GEO_FRONT,
GEO_BACK, GEO_TEXT, GEO_TEXTBACKGROUND, GEO_FOURTH,
GEO_NPCLEPUSMAG, GEO_STATION, GEO_SNIPERRIFLE, GEO_DART,
GEO_CROSSHAIR, GEO_HELM, GEO_MIKE, GEO_ALIEN,
GEO_TELEPORTER, GEO_PINGUBODY, GEO_PINGULH, GEO_PINGURH,
GEO_BOX, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Public Member Functions
Sp2_SpaceRace ()
~Sp2_SpaceRace ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
unsigned m_parameters [U_TOTAL]
Camera3 camera
CameraTPS camera2
CameraTPS camera3
float LSPEED
bool b_lightEnabled
int screenWidth
int screenHeight
Vector3 tempPos
bool b_enabletps
bool b_tpsDebounce
bool b_isWorn
float tpsTimer
int racePosition
bool b_raceBegin
bool b_raceStart
bool b_raceEnd
float f_endTimer
float f_raceCountdown
bool win
bool b_raceBegin2
bool b_raceStart2
bool b_raceEnd2
float f_endTimer2
SpaceVehicles frpc
SpaceVehicles frpc2
Player player
Alien spaceRaceNpc
Alien race2PNpc
Buildings spaceStationtp
vector< string > tasklist
Quest * questPtr
vector< GameObject * > collisionVec
PMAP racetrack
queue< int > racePath
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSkybox (Camera cam)
void RenderGameObj (GameObject x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
void RenderGameObj (Mesh *mesh, Vector3 pos, Vector3 scale, Vector3 rotate)
void RenderGameChar (GameChar x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
void RenderTeleporter (GameObject x, Mesh *mesh, string text, Vector3 scale)
void Renderfps ()
void Rendertps ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderMeshOnScreen (Mesh *mesh, Vector3 translate=Vector3(0, 0, 0), Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
Private Attributes
unsigned m_vertexArrayID
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_indexBuffer [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
MS viewStack2
float f_rotateCube
Mesh * meshList [NUM_GEOMETRY]
Light light [1]
Detailed Description
Class for the Space Race Scene inheriting from Scene /*.
Class Sp2_SpaceRace:
Definition at line 53 of file Sp2_SpaceRace.h.
Member Enumeration Documentation
enum Sp2_SpaceRace::GEOMETRY_TYPE
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_TEXT
GEO_TEXTBACKGROUND
GEO_FOURTH
GEO_NPCLEPUSMAG
GEO_STATION
GEO_SNIPERRIFLE
GEO_DART
GEO_CROSSHAIR
GEO_HELM
GEO_MIKE
GEO_ALIEN
GEO_TELEPORTER
GEO_PINGUBODY
GEO_PINGULH
GEO_PINGURH
GEO_BOX
NUM_GEOMETRY
Definition at line 64 of file Sp2_SpaceRace.h.
enum Sp2_SpaceRace::UNIFORM_TYPE
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 107 of file Sp2_SpaceRace.h.
Constructor & Destructor Documentation
Sp2_SpaceRace::Sp2_SpaceRace ()
Definition at line 17 of file Sp2_SpaceRace.cpp.
Sp2_SpaceRace::~Sp2_SpaceRace ()
Definition at line 21 of file Sp2_SpaceRace.cpp.
Member Function Documentation
void Sp2_SpaceRace::Exit () virtual
Implements Scene.
Definition at line 1014 of file Sp2_SpaceRace.cpp.
References m_programID, and m_vertexArrayID.
void Sp2_SpaceRace::Init () virtual
Implements Scene.
Definition at line 25 of file Sp2_SpaceRace.cpp.
References b_enabletps, b_raceBegin, b_raceBegin2, b_raceEnd, b_raceEnd2, b_raceStart, b_raceStart2, b_tpsDebounce, camera, camera2, camera3, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, f_endTimer, f_endTimer2, f_raceCountdown, frpc, frpc2, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ALIEN, GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_BOX, GEO_DART, GEO_FOURTH, GEO_FRONT, GEO_LEFT, GEO_LIGHTBALL, GEO_MIKE, GEO_NPCLEPUSMAG, GEO_QUAD, GEO_RIGHT, GEO_SNIPERRIFLE, GEO_TELEPORTER, GEO_TEXT, GEO_TEXTBACKGROUND, GEO_TOP, indexToVector(), CameraTPS::Init(), Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, load_map(), LoadShaders(), LoadTGA(), m_colorBuffer, m_indexBuffer, m_parameters, m_programID, m_vertexArrayID, m_vertexBuffer, m_window, meshList, NUM_GEOMETRY, player, Light::position, Light::power, race2PNpc, SpaceVehicles::racepath, racePath, racePosition, racetrack, GameChar::ReadFromTxt(), screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), spaceRaceNpc, spaceStationtp, Light::spotDirection, Mesh::textureID, toIndex(), tpsTimer, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void Sp2_SpaceRace::Render () virtual
Implements Scene.
Definition at line 923 of file Sp2_SpaceRace.cpp.
References SpaceVehicles::b_isInVehicle, b_raceBegin2, b_raceEnd2, b_raceStart2, camera, camera2, camera3, frpc, MS::LoadIdentity(), MS::LoadMatrix(), MS::LookAt(), Camera3::position, Camera::position, projectionStack, Renderfps(), Rendertps(), screenHeight, screenWidth, Mtx44::SetToPerspective(), Camera3::target, Camera::target, Camera3::up, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Sp2_SpaceRace::Renderfps () private
Definition at line 754 of file Sp2_SpaceRace.cpp.
References SpaceVehicles::b_isInVehicle, b_raceBegin, b_raceBegin2, b_raceEnd, b_raceEnd2, camera, sMap::data, f_raceCountdown, Alien::f_scaleBig, frpc, frpc2, GEO_ALIEN, GEO_AXES, GEO_BOX, GEO_FOURTH, GEO_TELEPORTER, GEO_TEXT, indexToVector(), SpaceVehicles::lap, light, m_parameters, meshList, modelStack, MS::PopMatrix(), GameObject::pos, Light::position, MS::PushMatrix(), race2PNpc, racePosition, racetrack, RenderGameChar(), RenderGameObj(), RenderMesh(), RenderSkybox(), RenderTeleporter(), RenderText(), RenderTextOnScreen(), MS::Rotate(), SpaceVehicles::rotationZ, MS::Scale(), spaceRaceNpc, spaceStationtp, SpaceVehicles::speed, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, viewStack, win, Vector3::x, Vector3::y, Position::y, Vector3::z, and Position::z.
Referenced by Render().
void Sp2_SpaceRace::RenderGameChar (GameChar x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 619 of file Sp2_SpaceRace.cpp.
References GameObject::boundary, GameChar::chat_boundary, collision(), GameChar::dialogue_index, GEO_TEXT, GameChar::isPressed, meshList, player, GameObject::pos, RenderGameObj(), RenderTextOnScreen(), and GameChar::vec_dialog.
Referenced by Renderfps(), and Rendertps().
void Sp2_SpaceRace::RenderGameObj (GameObject x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 580 of file Sp2_SpaceRace.cpp.
References GameObject::boundary, camera, collision(), GEO_TEXT, meshList, modelStack, MS::PopMatrix(), GameObject::pos, Camera3::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps(), RenderGameChar(), RenderTeleporter(), and Rendertps().
void Sp2_SpaceRace::RenderGameObj (Mesh * mesh, Vector3 pos, Vector3 scale, Vector3 rotate) private
Definition at line 605 of file Sp2_SpaceRace.cpp.
References modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void Sp2_SpaceRace::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 474 of file Sp2_SpaceRace.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Renderfps(), RenderGameObj(), RenderMeshOnScreen(), and RenderSkybox().
void Sp2_SpaceRace::RenderMeshOnScreen (Mesh * mesh, Vector3 translate = Vector3(0, 0, 0), Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 711 of file Sp2_SpaceRace.cpp.
References b_lightEnabled, MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Sp2_SpaceRace::RenderSkybox (Camera cam) private
Definition at line 517 of file Sp2_SpaceRace.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Renderfps(), and Rendertps().
void Sp2_SpaceRace::RenderTeleporter (GameObject x, Mesh * mesh, string text, Vector3 scale) private
Definition at line 735 of file Sp2_SpaceRace.cpp.
References collisionXZ(), GEO_TEXT, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderGameObj(), RenderText(), RenderTextOnScreen(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps(), and Rendertps().
void Sp2_SpaceRace::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 632 of file Sp2_SpaceRace.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Renderfps(), and RenderTeleporter().
void Sp2_SpaceRace::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 661 of file Sp2_SpaceRace.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Renderfps(), RenderGameChar(), RenderGameObj(), RenderTeleporter(), and Rendertps().
void Sp2_SpaceRace::Rendertps () private
Definition at line 859 of file Sp2_SpaceRace.cpp.
References SpaceVehicles::b_isInVehicle, b_raceBegin2, b_raceEnd2, camera, sMap::data, f_raceCountdown, Alien::f_scaleBig, frpc, frpc2, GEO_ALIEN, GEO_BOX, GEO_FOURTH, GEO_TELEPORTER, GEO_TEXT, indexToVector(), SpaceVehicles::lap, light, m_parameters, meshList, Light::position, race2PNpc, racePosition, racetrack, RenderGameChar(), RenderGameObj(), RenderSkybox(), RenderTeleporter(), RenderTextOnScreen(), SpaceVehicles::rotationZ, spaceRaceNpc, spaceStationtp, SpaceVehicles::speed, MS::Top(), U_LIGHT0_POSITION, viewStack, win, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void Sp2_SpaceRace::Update (double dt) virtual
Implements Scene.
Definition at line 242 of file Sp2_SpaceRace.cpp.
References CameraTPS::b_cameraLock, GameChar::b_dialogueEnd, b_enabletps, SpaceVehicles::b_isInVehicle, b_raceBegin, b_raceBegin2, b_raceEnd, b_raceEnd2, b_raceStart, b_raceStart2, b_tpsDebounce, camera, camera2, camera3, GameChar::chat_update(), collisionVec, collisionXZ(), f_endTimer, f_endTimer2, f_raceCountdown, frpc, frpc2, SpaceVehicles::getRacePosition(), indexToVector(), Application::IsKeyPressed(), SpaceVehicles::lap, SpaceVehicles::max_speed, Player::movementUpdate(), player, GameObject::pos, Alien::pulsingUpdate(), Player::questList, race2PNpc, SpaceVehicles::racepath, racePath, racePosition, racetrack, spaceRaceNpc, spaceStationtp, Application::switchToScene1(), toIndex(), tpsTimer, CameraTPS::tpsUpdateVec(), SpaceVehicles::updateCPUVehicle(), SpaceVehicles::updateVehicle(), SpaceVehicles::updateVehicle2(), and win.
Field Documentation
bool Sp2_SpaceRace::b_enabletps
Definition at line 145 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
bool Sp2_SpaceRace::b_isWorn
Definition at line 147 of file Sp2_SpaceRace.h.
bool Sp2_SpaceRace::b_lightEnabled
Definition at line 142 of file Sp2_SpaceRace.h.
Referenced by RenderMeshOnScreen().
bool Sp2_SpaceRace::b_raceBegin
Definition at line 152 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), and Update().
bool Sp2_SpaceRace::b_raceBegin2
Definition at line 159 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), Renderfps(), Rendertps(), and Update().
bool Sp2_SpaceRace::b_raceEnd
Definition at line 154 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), and Update().
bool Sp2_SpaceRace::b_raceEnd2
Definition at line 161 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), Renderfps(), Rendertps(), and Update().
bool Sp2_SpaceRace::b_raceStart
Definition at line 153 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
bool Sp2_SpaceRace::b_raceStart2
Definition at line 160 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), and Update().
bool Sp2_SpaceRace::b_tpsDebounce
Definition at line 146 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
Camera3 Sp2_SpaceRace::camera
Definition at line 138 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), Renderfps(), RenderGameObj(), Rendertps(), and Update().
CameraTPS Sp2_SpaceRace::camera2
Definition at line 139 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), and Update().
CameraTPS Sp2_SpaceRace::camera3
Definition at line 139 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), and Update().
vector<GameObject*> Sp2_SpaceRace::collisionVec
Definition at line 179 of file Sp2_SpaceRace.h.
Referenced by Update().
float Sp2_SpaceRace::f_endTimer
Definition at line 155 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
float Sp2_SpaceRace::f_endTimer2
Definition at line 162 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
float Sp2_SpaceRace::f_raceCountdown
Definition at line 156 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
float Sp2_SpaceRace::f_rotateCube private
Definition at line 193 of file Sp2_SpaceRace.h.
SpaceVehicles Sp2_SpaceRace::frpc
Definition at line 164 of file Sp2_SpaceRace.h.
Referenced by Init(), Render(), Renderfps(), Rendertps(), and Update().
SpaceVehicles Sp2_SpaceRace::frpc2
Definition at line 164 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
Light Sp2_SpaceRace::light[1] private
Definition at line 195 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), and Rendertps().
float Sp2_SpaceRace::LSPEED
Definition at line 141 of file Sp2_SpaceRace.h.
unsigned Sp2_SpaceRace::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 188 of file Sp2_SpaceRace.h.
Referenced by Init().
unsigned Sp2_SpaceRace::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 190 of file Sp2_SpaceRace.h.
Referenced by Init().
unsigned Sp2_SpaceRace::m_parameters[U_TOTAL]
Definition at line 136 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), RenderMesh(), RenderText(), RenderTextOnScreen(), and Rendertps().
unsigned Sp2_SpaceRace::m_programID private
Definition at line 189 of file Sp2_SpaceRace.h.
Referenced by Exit(), and Init().
unsigned Sp2_SpaceRace::m_vertexArrayID private
Definition at line 186 of file Sp2_SpaceRace.h.
Referenced by Exit(), and Init().
unsigned Sp2_SpaceRace::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 187 of file Sp2_SpaceRace.h.
Referenced by Init().
Mesh* Sp2_SpaceRace::meshList[NUM_GEOMETRY] private
Definition at line 194 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), RenderGameChar(), RenderGameObj(), RenderSkybox(), RenderTeleporter(), and Rendertps().
MS Sp2_SpaceRace::modelStack private
Definition at line 192 of file Sp2_SpaceRace.h.
Referenced by Renderfps(), RenderGameObj(), RenderMesh(), RenderMeshOnScreen(), RenderSkybox(), RenderTeleporter(), RenderText(), and RenderTextOnScreen().
Player Sp2_SpaceRace::player
Definition at line 167 of file Sp2_SpaceRace.h.
Referenced by Init(), RenderGameChar(), RenderTeleporter(), and Update().
MS Sp2_SpaceRace::projectionStack private
Definition at line 192 of file Sp2_SpaceRace.h.
Referenced by Render(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
Quest* Sp2_SpaceRace::questPtr
Definition at line 177 of file Sp2_SpaceRace.h.
Alien Sp2_SpaceRace::race2PNpc
Definition at line 170 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
queue<int> Sp2_SpaceRace::racePath
Definition at line 182 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
int Sp2_SpaceRace::racePosition
Definition at line 150 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
PMAP Sp2_SpaceRace::racetrack
Definition at line 181 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
int Sp2_SpaceRace::screenHeight
Definition at line 143 of file Sp2_SpaceRace.h.
Referenced by Init(), and Render().
int Sp2_SpaceRace::screenWidth
Definition at line 143 of file Sp2_SpaceRace.h.
Referenced by Init(), and Render().
Alien Sp2_SpaceRace::spaceRaceNpc
Definition at line 170 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
Buildings Sp2_SpaceRace::spaceStationtp
Definition at line 173 of file Sp2_SpaceRace.h.
Referenced by Init(), Renderfps(), Rendertps(), and Update().
vector<string> Sp2_SpaceRace::tasklist
Definition at line 176 of file Sp2_SpaceRace.h.
Vector3 Sp2_SpaceRace::tempPos
Definition at line 144 of file Sp2_SpaceRace.h.
float Sp2_SpaceRace::tpsTimer
Definition at line 148 of file Sp2_SpaceRace.h.
Referenced by Init(), and Update().
MS Sp2_SpaceRace::viewStack private
Definition at line 192 of file Sp2_SpaceRace.h.
Referenced by Render(), Renderfps(), RenderMesh(), RenderMeshOnScreen(), RenderText(), RenderTextOnScreen(), and Rendertps().
MS Sp2_SpaceRace::viewStack2 private
Definition at line 192 of file Sp2_SpaceRace.h.
bool Sp2_SpaceRace::win
Definition at line 157 of file Sp2_SpaceRace.h.
Referenced by Renderfps(), Rendertps(), and Update().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Sp2_SpaceRace.h
Computer Graphics/Source/Sp2_SpaceRace.cpp