My Application: Application Class Reference
Application Class Reference
Class for Application /*.
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
static void switchToScene1 ()
static void switchToScene2 ()
static void switchToScene3 ()
static void playSound (int index, bool loop)
Private Attributes
StopWatch m_timer
Static Private Attributes
static Music * music
static Scene * scene
static Scene * scene1
static Scene * scene2
static Scene * scene3
Detailed Description
Class for Application /*.
Class Application:
Definition at line 32 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 44 of file Application.cpp.
Application::~Application ()
Definition at line 48 of file Application.cpp.
Member Function Documentation
void Application::Exit ()
Definition at line 182 of file Application.cpp.
References m_window.
Referenced by main().
void Application::Init ()
Definition at line 59 of file Application.cpp.
References error_callback(), key_callback(), m_window, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 39 of file Application.cpp.
Referenced by GameChar::chat_update(), SpaceVehicles::enterVehicleUpdate(), Player::movementUpdate(), Run(), CameraTPS::tpsUpdateVec(), Camera3::Update(), LoadingScene::Update(), Sp2_Scene1::Update(), Sp2_Scene3::Update(), Sp2_SpaceRace::Update(), SpaceVehicles::updateVehicle(), and SpaceVehicles::updateVehicle2().
void Application::playSound (int index, bool loop) static
Definition at line 133 of file Application.cpp.
References music, and Music::OpeningMusic().
void Application::Run ()
Definition at line 138 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Scene::Init(), Music::Init(), IsKeyPressed(), m_timer, m_window, music, Player::questList, Scene::Render(), scene, scene1, scene2, scene3, StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
void Application::switchToScene1 () static
Definition at line 116 of file Application.cpp.
References scene, and scene1.
Referenced by Sp2_Scene3::Update(), and Sp2_SpaceRace::Update().
void Application::switchToScene2 () static
Definition at line 121 of file Application.cpp.
References scene, and scene2.
Referenced by Sp2_Scene1::Update().
void Application::switchToScene3 () static
Definition at line 126 of file Application.cpp.
References scene, and scene3.
Referenced by Sp2_Scene1::Update().
Field Documentation
StopWatch Application::m_timer private
Definition at line 54 of file Application.h.
Referenced by Run().
Music * Application::music static private
Definition at line 48 of file Application.h.
Referenced by playSound(), and Run().
Scene * Application::scene static private
Definition at line 49 of file Application.h.
Referenced by Run(), switchToScene1(), switchToScene2(), and switchToScene3().
Scene * Application::scene1 static private
Definition at line 50 of file Application.h.
Referenced by Run(), and switchToScene1().
Scene * Application::scene2 static private
Definition at line 51 of file Application.h.
Referenced by Run(), and switchToScene2().
Scene * Application::scene3 static private
Definition at line 52 of file Application.h.
Referenced by Run(), and switchToScene3().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Application.h
Computer Graphics/Source/Application.cpp