My Application: irrklang::CIrrKlangAudioStreamMP3 Class Reference
irrklang::CIrrKlangAudioStreamMP3 Class Reference
Reads and decodes audio data into an usable audio stream for the ISoundEngine.
#include <CIrrKlangAudioStreamMP3.h>
Data Structures
class QueueBuffer
struct SFramePositionData
Public Member Functions
CIrrKlangAudioStreamMP3 (IFileReader *file)
~CIrrKlangAudioStreamMP3 ()
virtual SAudioStreamFormat getFormat ()
returns format of the audio stream
virtual ik_s32 readFrames (void *target, ik_s32 frameCountToRead)
tells the audio stream to read n audio frames into the specified buffer
virtual bool setPosition (ik_s32 pos)
sets the position of the audio stream.
bool isOK ()
Public Member Functions inherited from irrklang::IAudioStream
virtual ~IAudioStream ()
destructor
virtual bool getIsSeekingSupported ()
returns true if the audio stream is seekable
Public Member Functions inherited from irrklang::IRefCounted
IRefCounted ()
Constructor.
virtual ~IRefCounted ()
Destructor.
void grab ()
Grabs the object.
bool drop ()
When you receive an object in irrKlang (for example an ISound using play2D() or play3D()), and you no longer need the object, you have to call drop().
Protected Member Functions
ik_s32 readFrameForMP3 (void *target, ik_s32 frameCountToRead, bool parseOnly=false)
bool decodeFrame ()
void skipID3IfNecessary ()
Protected Attributes
irrklang::IFileReader * File
SAudioStreamFormat Format
MPAuDecContext * TheMPAuDecContext
ik_u8 InputBuffer [IKP_MP3_INPUT_BUFFER_SIZE]
int InputPosition
int InputLength
int Position
ik_u8 * DecodeBuffer
ik_s32 FileBegin
ik_u32 CurrentFramePosition
bool FirstFrameRead
bool EndOfFileReached
std::vector< SFramePositionData > FramePositionData
QueueBuffer DecodedQueue
Detailed Description
Reads and decodes audio data into an usable audio stream for the ISoundEngine.
To extend irrKlang with new audio format decoders, the only thing needed to do is implementing the IAudioStream interface. All the code available in this class is only for mp3 decoding and may make this class look a bit more complicated then it actually is.
Definition at line 23 of file CIrrKlangAudioStreamMP3.h.
Constructor & Destructor Documentation
irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3 (IFileReader * file)
Definition at line 15 of file CIrrKlangAudioStreamMP3.cpp.
References MPAuDecContext::channels, MPAuDecContext::coded_frame_size, DecodeBuffer, decodeFrame(), irrklang::IRefCounted::drop(), EndOfFileReached, File, Format, MPAuDecContext::frame_size, irrklang::SAudioStreamFormat::FrameCount, FramePositionData, irrklang::IFileReader::getPos(), irrklang::IFileReader::getSize(), irrklang::IRefCounted::grab(), InputLength, InputPosition, mpaudec_init(), MPAUDEC_MAX_AUDIO_FRAME_SIZE, irrklang::CIrrKlangAudioStreamMP3::SFramePositionData::offset, MPAuDecContext::parse_only, MPAuDecContext::sample_rate, setPosition(), irrklang::CIrrKlangAudioStreamMP3::SFramePositionData::size, skipID3IfNecessary(), and TheMPAuDecContext.
irrklang::CIrrKlangAudioStreamMP3::~CIrrKlangAudioStreamMP3 ()
Definition at line 86 of file CIrrKlangAudioStreamMP3.cpp.
References DecodeBuffer, irrklang::IRefCounted::drop(), File, mpaudec_clear(), and TheMPAuDecContext.
Member Function Documentation
bool irrklang::CIrrKlangAudioStreamMP3::decodeFrame () protected
Definition at line 146 of file CIrrKlangAudioStreamMP3.cpp.
References irrklang::SAudioStreamFormat::ChannelCount, MPAuDecContext::channels, DecodeBuffer, DecodedQueue, EndOfFileReached, irrklang::ESF_S16, File, FirstFrameRead, Format, MPAuDecContext::frame_size, irrklang::SAudioStreamFormat::FrameCount, irrklang::SAudioStreamFormat::getFrameSize(), irrklang::IKP_MP3_INPUT_BUFFER_SIZE, InputBuffer, InputLength, InputPosition, mpaudec_decode_frame(), MPAuDecContext::parse_only, irrklang::IFileReader::read(), MPAuDecContext::sample_rate, irrklang::SAudioStreamFormat::SampleFormat, irrklang::SAudioStreamFormat::SampleRate, TheMPAuDecContext, and irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::write().
Referenced by CIrrKlangAudioStreamMP3(), readFrames(), and setPosition().
SAudioStreamFormat irrklang::CIrrKlangAudioStreamMP3::getFormat () virtual
returns format of the audio stream
Implements irrklang::IAudioStream.
Definition at line 103 of file CIrrKlangAudioStreamMP3.cpp.
References Format.
bool irrklang::CIrrKlangAudioStreamMP3::isOK () inline
Definition at line 47 of file CIrrKlangAudioStreamMP3.h.
References File.
Referenced by irrklang::CIrrKlangAudioStreamLoaderMP3::createAudioStream().
ik_s32 irrklang::CIrrKlangAudioStreamMP3::readFrameForMP3 (void * target, ik_s32 frameCountToRead, bool parseOnly = false) protected
ik_s32 irrklang::CIrrKlangAudioStreamMP3::readFrames (void * target, ik_s32 frameCountToRead) virtual
tells the audio stream to read n audio frames into the specified buffer
Parameters
target Target data buffer to the method will write the read frames into. The specified buffer will be getFormat().getFrameSize()*frameCount big.
frameCount amount of frames to be read.
Returns
Returns amount of frames really read. Should be frameCountToRead in most cases.
Implements irrklang::IAudioStream.
Definition at line 110 of file CIrrKlangAudioStreamMP3.cpp.
References DecodedQueue, decodeFrame(), EndOfFileReached, Format, irrklang::SAudioStreamFormat::getFrameSize(), irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::getSize(), and irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::read().
Referenced by setPosition().
bool irrklang::CIrrKlangAudioStreamMP3::setPosition (ik_s32 pos) virtual
sets the position of the audio stream.
For example to let the stream be read from the beginning of the file again, setPosition(0) would be called. This is usually done be the sound engine to loop a stream after if has reached the end. Return true if sucessful and 0 if not.
Implements irrklang::IAudioStream.
Definition at line 215 of file CIrrKlangAudioStreamMP3.cpp.
References MPAuDecContext::bit_rate, MPAuDecContext::channels, irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::clear(), CurrentFramePosition, DecodedQueue, decodeFrame(), EndOfFileReached, File, FileBegin, Format, MPAuDecContext::frame_size, FramePositionData, irrklang::SAudioStreamFormat::getFrameSize(), InputLength, InputPosition, mpaudec_clear(), mpaudec_init(), Position, readFrames(), MPAuDecContext::sample_rate, irrklang::IFileReader::seek(), and TheMPAuDecContext.
Referenced by CIrrKlangAudioStreamMP3().
void irrklang::CIrrKlangAudioStreamMP3::skipID3IfNecessary () protected
Definition at line 366 of file CIrrKlangAudioStreamMP3.cpp.
References File, FileBegin, irrklang::IFileReader::read(), and irrklang::IFileReader::seek().
Referenced by CIrrKlangAudioStreamMP3().
Field Documentation
ik_u32 irrklang::CIrrKlangAudioStreamMP3::CurrentFramePosition protected
Definition at line 68 of file CIrrKlangAudioStreamMP3.h.
Referenced by setPosition().
ik_u8* irrklang::CIrrKlangAudioStreamMP3::DecodeBuffer protected
Definition at line 66 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), and ~CIrrKlangAudioStreamMP3().
QueueBuffer irrklang::CIrrKlangAudioStreamMP3::DecodedQueue protected
Definition at line 100 of file CIrrKlangAudioStreamMP3.h.
Referenced by decodeFrame(), readFrames(), and setPosition().
bool irrklang::CIrrKlangAudioStreamMP3::EndOfFileReached protected
Definition at line 71 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), readFrames(), and setPosition().
irrklang::IFileReader* irrklang::CIrrKlangAudioStreamMP3::File protected
Definition at line 55 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), isOK(), setPosition(), skipID3IfNecessary(), and ~CIrrKlangAudioStreamMP3().
ik_s32 irrklang::CIrrKlangAudioStreamMP3::FileBegin protected
Definition at line 67 of file CIrrKlangAudioStreamMP3.h.
Referenced by setPosition(), and skipID3IfNecessary().
bool irrklang::CIrrKlangAudioStreamMP3::FirstFrameRead protected
Definition at line 70 of file CIrrKlangAudioStreamMP3.h.
Referenced by decodeFrame().
SAudioStreamFormat irrklang::CIrrKlangAudioStreamMP3::Format protected
Definition at line 56 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), getFormat(), readFrames(), and setPosition().
std::vector<SFramePositionData> irrklang::CIrrKlangAudioStreamMP3::FramePositionData protected
Definition at line 99 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), and setPosition().
ik_u8 irrklang::CIrrKlangAudioStreamMP3::InputBuffer[IKP_MP3_INPUT_BUFFER_SIZE] protected
Definition at line 61 of file CIrrKlangAudioStreamMP3.h.
Referenced by decodeFrame().
int irrklang::CIrrKlangAudioStreamMP3::InputLength protected
Definition at line 64 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), and setPosition().
int irrklang::CIrrKlangAudioStreamMP3::InputPosition protected
Definition at line 63 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), and setPosition().
int irrklang::CIrrKlangAudioStreamMP3::Position protected
Definition at line 65 of file CIrrKlangAudioStreamMP3.h.
Referenced by setPosition().
MPAuDecContext* irrklang::CIrrKlangAudioStreamMP3::TheMPAuDecContext protected
Definition at line 59 of file CIrrKlangAudioStreamMP3.h.
Referenced by CIrrKlangAudioStreamMP3(), decodeFrame(), setPosition(), and ~CIrrKlangAudioStreamMP3().
The documentation for this class was generated from the following files:
Computer Graphics/irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamMP3.h
Computer Graphics/irrKlang/plugins/ikpMP3/CIrrKlangAudioStreamMP3.cpp