My Application: SpaceVehicles Class Reference
SpaceVehicles Class Reference
Class for Space Vehicles inheriting from GameObject /*.
#include <SpaceVehicles.h>
Public Member Functions
SpaceVehicles ()
SpaceVehicles (string object_name, int boundary, float viewAngle, Vector3 pos, int max_speed=150)
~SpaceVehicles ()
void updateVehicle (double deltaTime)
void updateVehicle (double deltaTime, PMAP map, queue< int > &q)
void updateVehicle2 (double deltaTime, PMAP map, queue< int > &q)
void enterVehicleUpdate (Player &player)
void updateCPUVehicle (double deltaTime, PMAP map, queue< int > &q)
int getRacePosition (SpaceVehicles x, int startIndex)
int positionInQueue (int index)
float distanceFromCheckpoint ()
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Data Fields
float speed
bool b_isInVehicle
bool b_vehDebounce
float rotationZ
int lap
bool lapDebounce
int max_speed
queue< int > racepath
Data Fields inherited from GameObject
string name
int boundary
Vector3 pos
float viewAngle
Static Public Attributes
static size_t SV_count = 0
Private Attributes
float acceleration
float rotateAngle
Additional Inherited Members
Protected Member Functions inherited from GameObject
GameObject ()
GameObject (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
Detailed Description
Class for Space Vehicles inheriting from GameObject /*.
Class SpaceVehicles:
Definition at line 31 of file SpaceVehicles.h.
Constructor & Destructor Documentation
SpaceVehicles::SpaceVehicles ()
Definition at line 5 of file SpaceVehicles.cpp.
References b_isInVehicle, b_vehDebounce, lap, lapDebounce, and SV_count.
SpaceVehicles::SpaceVehicles (string object_name, int boundary, float viewAngle, Vector3 pos, int max_speed = 150)
Definition at line 14 of file SpaceVehicles.cpp.
References b_isInVehicle, b_vehDebounce, lap, lapDebounce, and rotationZ.
SpaceVehicles::~SpaceVehicles ()
Definition at line 23 of file SpaceVehicles.cpp.
References SV_count.
Member Function Documentation
float SpaceVehicles::distanceFromCheckpoint ()
Definition at line 494 of file SpaceVehicles.cpp.
References indexToVector(), Vector3::Length(), GameObject::pos, and racepath.
Referenced by getRacePosition().
void SpaceVehicles::enterVehicleUpdate (Player & player)
Definition at line 356 of file SpaceVehicles.cpp.
References b_isInVehicle, b_vehDebounce, GameObject::boundary, collision(), Application::IsKeyPressed(), and GameObject::pos.
int SpaceVehicles::getRacePosition (SpaceVehicles x, int startIndex)
Definition at line 440 of file SpaceVehicles.cpp.
References distanceFromCheckpoint(), lap, positionInQueue(), and racepath.
Referenced by Sp2_SpaceRace::Update().
int SpaceVehicles::positionInQueue (int index)
Definition at line 477 of file SpaceVehicles.cpp.
References GameObject::pos, and racepath.
Referenced by getRacePosition().
void SpaceVehicles::updateCPUVehicle (double deltaTime, PMAP map, queue< int > & q)
Definition at line 375 of file SpaceVehicles.cpp.
References acceleration, collision(), sMap::data, Math::DegreeToRadian(), indexToVector(), lap, lapDebounce, max_speed, GameObject::pos, Math::RadianToDegree(), speed, vectorToIndex(), GameObject::viewAngle, Vector3::x, and Vector3::z.
Referenced by Sp2_SpaceRace::Update().
void SpaceVehicles::updateVehicle (double deltaTime)
Definition at line 29 of file SpaceVehicles.cpp.
References acceleration, Math::DegreeToRadian(), Application::IsKeyPressed(), max_speed, GameObject::pos, rotateAngle, rotationZ, speed, GameObject::viewAngle, Vector3::x, and Vector3::z.
Referenced by Sp2_SpaceRace::Update().
void SpaceVehicles::updateVehicle (double deltaTime, PMAP map, queue< int > & q)
Definition at line 115 of file SpaceVehicles.cpp.
References acceleration, collision(), sMap::data, Math::DegreeToRadian(), indexToVector(), Application::IsKeyPressed(), lap, lapDebounce, max_speed, GameObject::pos, rotateAngle, rotationZ, speed, vectorToIndex(), GameObject::viewAngle, Vector3::x, and Vector3::z.
void SpaceVehicles::updateVehicle2 (double deltaTime, PMAP map, queue< int > & q)
Definition at line 236 of file SpaceVehicles.cpp.
References acceleration, collision(), sMap::data, Math::DegreeToRadian(), indexToVector(), Application::IsKeyPressed(), lap, lapDebounce, max_speed, GameObject::pos, rotateAngle, rotationZ, speed, vectorToIndex(), GameObject::viewAngle, Vector3::x, and Vector3::z.
Referenced by Sp2_SpaceRace::Update().
Field Documentation
float SpaceVehicles::acceleration private
Definition at line 60 of file SpaceVehicles.h.
Referenced by updateCPUVehicle(), updateVehicle(), and updateVehicle2().
bool SpaceVehicles::b_isInVehicle
Definition at line 40 of file SpaceVehicles.h.
Referenced by enterVehicleUpdate(), Sp2_Scene3::Render(), Sp2_SpaceRace::Render(), Sp2_SpaceRace::Renderfps(), Sp2_SpaceRace::Rendertps(), SpaceVehicles(), Sp2_Scene3::Update(), and Sp2_SpaceRace::Update().
bool SpaceVehicles::b_vehDebounce
Definition at line 41 of file SpaceVehicles.h.
Referenced by enterVehicleUpdate(), and SpaceVehicles().
int SpaceVehicles::lap
Definition at line 43 of file SpaceVehicles.h.
Referenced by getRacePosition(), Sp2_SpaceRace::Renderfps(), Sp2_SpaceRace::Rendertps(), SpaceVehicles(), Sp2_SpaceRace::Update(), updateCPUVehicle(), updateVehicle(), and updateVehicle2().
bool SpaceVehicles::lapDebounce
Definition at line 44 of file SpaceVehicles.h.
Referenced by SpaceVehicles(), updateCPUVehicle(), updateVehicle(), and updateVehicle2().
int SpaceVehicles::max_speed
Definition at line 45 of file SpaceVehicles.h.
Referenced by Sp2_SpaceRace::Update(), updateCPUVehicle(), updateVehicle(), and updateVehicle2().
queue<int> SpaceVehicles::racepath
Definition at line 46 of file SpaceVehicles.h.
Referenced by distanceFromCheckpoint(), getRacePosition(), Sp2_SpaceRace::Init(), positionInQueue(), and Sp2_SpaceRace::Update().
float SpaceVehicles::rotateAngle private
Definition at line 61 of file SpaceVehicles.h.
Referenced by updateVehicle(), and updateVehicle2().
float SpaceVehicles::rotationZ
Definition at line 42 of file SpaceVehicles.h.
Referenced by Sp2_SpaceRace::Renderfps(), Sp2_SpaceRace::Rendertps(), SpaceVehicles(), updateVehicle(), and updateVehicle2().
float SpaceVehicles::speed
Definition at line 39 of file SpaceVehicles.h.
Referenced by Sp2_SpaceRace::Renderfps(), Sp2_SpaceRace::Rendertps(), updateCPUVehicle(), updateVehicle(), and updateVehicle2().
size_t SpaceVehicles::SV_count = 0 static
Definition at line 37 of file SpaceVehicles.h.
Referenced by SpaceVehicles(), and ~SpaceVehicles().
The documentation for this class was generated from the following files:
Computer Graphics/Source/SpaceVehicles.h
Computer Graphics/Source/SpaceVehicles.cpp