My Application: Sp2_Scene3 Class Reference
Sp2_Scene3 Class Reference
Defines a game level with platforming elements and game objects, npc, enemies and platforms etc.
#include <SP2_Scene3.h>
Public Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, GEO_LEFT,
GEO_RIGHT, GEO_TOP, GEO_BOTTOM, GEO_FRONT,
GEO_BACK, GEO_TEXT, GEO_TEXT2, GEO_TEXTBACKGROUND,
GEO_FOURTH, GEO_NPCLEPUSMAG, GEO_STATION, GEO_SNIPERRIFLE,
GEO_DART, GEO_CROSSHAIR, GEO_SUIT, GEO_HELM,
GEO_GUIDEHELM, GEO_GUIDEBODY, GEO_GUIDEARMLEFT, GEO_GUIDEARMRIGHT,
GEO_MIKE, GEO_NPC3, GEO_FLIGHTUI, GEO_HELMETUI,
GEO_BB8H, GEO_BB8B, GEO_BB8v2H, GEO_BB8v2B,
GEO_PINGU, GEO_CHESTBURSTER, GEO_NECROMANCER, GEO_PLATFORM,
GEO_LADDER, GEO_PINGUBODY, GEO_PINGULH, GEO_PINGURH,
GEO_BOX, GEO_TABLE, GEO_CHAIR, GEO_KEYCARD,
GEO_DEATHSCREEN, GEO_MEDICBODY, GEO_MEDICHEAD, GEO_MEDICARM1,
GEO_MEDICARM2, GEO_TELEPORTER, GEO_ROCKET, GEO_ARROW,
GEO_JERRYCAN, GEO_SPACEVIEW, GEO_EARTH, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Public Member Functions
Sp2_Scene3 ()
Default constructor.
~Sp2_Scene3 ()
Default destructor.
virtual void Init ()
Init scene with game objects, light and camera positions, properties like light power. Loads OBJ and texture into scene.
virtual void Update (double dt)
Updates health system, collision, platform, player, camera and enemy behaviours.
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
unsigned m_parameters [U_TOTAL]
Camera3 camera
CameraTPS camera2
float LSPEED
bool b_lightEnabled
int screenWidth
int screenHeight
Vector3 tempPos
bool b_enabletps
bool b_tpsDebounce
bool b_isWorn
bool b_isDisplayUI
bool b_isClimb
bool b_isClimb2
bool b_isClimb3
bool b_isClimb4
bool b_isClimb6
bool b_switchDir
bool b_collectBox1
bool b_collectBox2
bool b_collectBox3
bool b_isLand
bool isFinished
float horiDist
float verticalDistance
float rotateHelm
float scaleHelm
float tpsTimer
int landDist
Vector3 oldPos
SpaceVehicles np
SpaceVehicles frpc
Buildings station
Alien mike1
Alien mike2
Alien mike3
Human whale
Human suit
Human spaceHelm
BB8 BB8_
BB8v2 BB8v2_
Medic Medic_
Pingu Pingu_
Quest raceQuest
AlienEnemy ChestBurster
AlienEnemy Necromancer
AlienEnemy ChestBurster1
Sir Sir_
Platform Platform_
Platform Platform1
Platform Platform2
Platform Platform3
Platform Platform4
Platform Platform5
Platform Platform6
Platform Platform7
Platform Platform8
Platform Platform9
Platform Platform10
Player player
Buildings box1
Buildings box2
Buildings box3
Buildings box4
Buildings table1
Buildings chair1
Buildings keycard1
Buildings ladder
Buildings ladder2
Buildings ladder3
Buildings ladder4
Buildings rocket
Buildings jerrycan
Buildings earth
Buildings spaceStationTp
Buildings Arrow
vector< string > tasklist
Quest * questPtr
vector< GameObject * > collisionVec
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Render mesh such as basic primitive shapes and OBJs.
void RenderSkybox ()
void RenderSpaceVehicles (Camera3 camera)
void RenderPingu ()
void RenderBB8 (BB8 x)
void RenderBB8v2 (BB8v2 n)
void RenderSuit ()
Rendering of the in-game suit interface and positions.
void RenderChestBurster ()
void RenderNecromancer ()
void RenderChestBurster1 ()
void RenderSir ()
void RenderPlatform (Platform p, bool isRotate)
Renders all platforms.
void RenderMedic (Medic x)
void RenderGameObj (GameObject x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1), smaller axis=0)
void RenderGameChar (GameChar x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1))
void RenderTeleporter (GameObject x, Mesh *mesh, string text, Vector3 scale)
void RenderRocket ()
void RenderInstructions (GameObject x, Mesh *mesh, string text, Vector3 scale)
void Renderfps ()
void Rendertps ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderMeshOnScreen (Mesh *mesh, Vector3 translate=Vector3(0, 0, 0), Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
Private Attributes
unsigned m_vertexArrayID
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_indexBuffer [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
MS viewStack2
float f_rotateCube
Mesh * meshList [NUM_GEOMETRY]
Light light [1]
Detailed Description
Defines a game level with platforming elements and game objects, npc, enemies and platforms etc.
Class Sp2_Scene3:
Definition at line 48 of file SP2_Scene3.h.
Member Enumeration Documentation
enum Sp2_Scene3::GEOMETRY_TYPE
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_TEXT
GEO_TEXT2
GEO_TEXTBACKGROUND
GEO_FOURTH
GEO_NPCLEPUSMAG
GEO_STATION
GEO_SNIPERRIFLE
GEO_DART
GEO_CROSSHAIR
GEO_SUIT
GEO_HELM
GEO_GUIDEHELM
GEO_GUIDEBODY
GEO_GUIDEARMLEFT
GEO_GUIDEARMRIGHT
GEO_MIKE
GEO_NPC3
GEO_FLIGHTUI
GEO_HELMETUI
GEO_BB8H
GEO_BB8B
GEO_BB8v2H
GEO_BB8v2B
GEO_PINGU
GEO_CHESTBURSTER
GEO_NECROMANCER
GEO_PLATFORM
GEO_LADDER
GEO_PINGUBODY
GEO_PINGULH
GEO_PINGURH
GEO_BOX
GEO_TABLE
GEO_CHAIR
GEO_KEYCARD
GEO_DEATHSCREEN
GEO_MEDICBODY
GEO_MEDICHEAD
GEO_MEDICARM1
GEO_MEDICARM2
GEO_TELEPORTER
GEO_ROCKET
GEO_ARROW
GEO_JERRYCAN
GEO_SPACEVIEW
GEO_EARTH
NUM_GEOMETRY
Definition at line 59 of file SP2_Scene3.h.
enum Sp2_Scene3::UNIFORM_TYPE
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 133 of file SP2_Scene3.h.
Constructor & Destructor Documentation
Sp2_Scene3::Sp2_Scene3 ()
Default constructor.
Definition at line 35 of file SP2_Scene3.cpp.
Sp2_Scene3::~Sp2_Scene3 ()
Default destructor.
Definition at line 46 of file SP2_Scene3.cpp.
Member Function Documentation
void Sp2_Scene3::Exit () virtual
Implements Scene.
Definition at line 1585 of file SP2_Scene3.cpp.
References m_programID, and m_vertexArrayID.
void Sp2_Scene3::Init () virtual
Init scene with game objects, light and camera positions, properties like light power. Loads OBJ and texture into scene.
*<—Under Construction—>*/
Implements Scene.
Definition at line 56 of file SP2_Scene3.cpp.
References Arrow, b_collectBox1, b_collectBox2, b_collectBox3, b_enabletps, b_isClimb, b_isClimb2, b_isClimb3, b_isClimb4, b_isClimb6, b_isDisplayUI, b_isLand, b_isWorn, b_switchDir, b_tpsDebounce, BB8v2_, box1, box2, box3, box4, camera, ChestBurster1, collisionVec, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), earth, Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BB8v2B, GEO_BB8v2H, GEO_BOTTOM, GEO_BOX, GEO_CHESTBURSTER, GEO_DEATHSCREEN, GEO_FRONT, GEO_GUIDEARMLEFT, GEO_GUIDEARMRIGHT, GEO_GUIDEBODY, GEO_GUIDEHELM, GEO_HELM, GEO_HELMETUI, GEO_JERRYCAN, GEO_LADDER, GEO_LEFT, GEO_LIGHTBALL, GEO_MEDICARM1, GEO_MEDICARM2, GEO_MEDICBODY, GEO_MEDICHEAD, GEO_NECROMANCER, GEO_PLATFORM, GEO_QUAD, GEO_RIGHT, GEO_ROCKET, GEO_SUIT, GEO_TELEPORTER, GEO_TEXT, GEO_TEXT2, GEO_TEXTBACKGROUND, GEO_TOP, horiDist, Camera3::Init(), isFinished, jerrycan, Light::kC, Light::kL, Light::kQ, ladder, ladder2, ladder3, ladder4, landDist, light, Light::LIGHT_SPOT, LoadShaders(), LoadTGA(), m_colorBuffer, m_indexBuffer, m_parameters, m_programID, m_vertexArrayID, m_vertexBuffer, m_window, Medic_, meshList, Necromancer, NUM_GEOMETRY, Player::oxygen, Platform1, Platform10, Platform2, Platform3, Platform4, Platform5, Platform6, Platform7, Platform8, Platform9, Platform_, player, Light::position, Camera3::position, Light::power, GameChar::ReadFromTxt(), rocket, rotateHelm, scaleHelm, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Sir_, spaceHelm, spaceStationTp, Light::spotDirection, suit, Mesh::textureID, tpsTimer, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, and verticalDistance.
void Sp2_Scene3::Render () virtual
Implements Scene.
Definition at line 1527 of file SP2_Scene3.cpp.
References b_enabletps, SpaceVehicles::b_isInVehicle, camera, camera2, frpc, MS::LoadIdentity(), MS::LoadMatrix(), MS::LookAt(), Camera3::position, Camera::position, projectionStack, Renderfps(), Rendertps(), screenHeight, screenWidth, Mtx44::SetToPerspective(), Camera3::target, Camera::target, Camera3::up, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Sp2_Scene3::RenderBB8 (BB8 x) private
void Sp2_Scene3::RenderBB8v2 (BB8v2 n) private
Definition at line 919 of file SP2_Scene3.cpp.
References GameObject::boundary, camera, GameChar::chat_boundary, collision(), GameChar::dialogue_index, GEO_BB8v2B, GEO_BB8v2H, GEO_TEXT, GameChar::isPressed, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, Camera3::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), MS::Translate(), GameChar::vec_dialog, GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderChestBurster () private
Definition at line 1251 of file SP2_Scene3.cpp.
References GEO_CHESTBURSTER, meshList, modelStack, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, AlienEnemy::wormrotating, AlienEnemy::wormtranslating, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderChestBurster1 () private
Definition at line 1269 of file SP2_Scene3.cpp.
References ChestBurster1, GEO_CHESTBURSTER, meshList, modelStack, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, AlienEnemy::wormrotating, AlienEnemy::wormtranslating, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::Renderfps () private
Definition at line 1444 of file SP2_Scene3.cpp.
References Arrow, b_collectBox1, b_collectBox2, b_collectBox3, BB8v2_, box1, box2, box4, GEO_ARROW, GEO_AXES, GEO_BOX, GEO_DEATHSCREEN, GEO_JERRYCAN, GEO_LADDER, GEO_LIGHTBALL, GEO_TELEPORTER, GEO_TEXT, GameChar::isDead(), isFinished, jerrycan, ladder, ladder2, ladder3, ladder4, light, m_parameters, Medic_, meshList, modelStack, Platform1, Platform2, Platform3, Platform4, Platform5, Platform_, player, MS::PopMatrix(), Light::position, MS::PushMatrix(), RenderBB8v2(), RenderChestBurster(), RenderChestBurster1(), RenderGameObj(), RenderInstructions(), RenderMedic(), RenderMesh(), RenderMeshOnScreen(), RenderNecromancer(), RenderPlatform(), RenderRocket(), RenderSir(), RenderSkybox(), RenderSuit(), RenderTeleporter(), RenderTextOnScreen(), spaceStationTp, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, viewStack, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void Sp2_Scene3::RenderGameChar (GameChar x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1)) private
Definition at line 901 of file SP2_Scene3.cpp.
References GameObject::boundary, GameChar::chat_boundary, collision(), GameChar::dialogue_index, GEO_TEXT, GameChar::isPressed, meshList, player, GameObject::pos, RenderGameObj(), RenderTextOnScreen(), and GameChar::vec_dialog.
void Sp2_Scene3::RenderGameObj (GameObject x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1), smaller axis = 0) private
Definition at line 873 of file SP2_Scene3.cpp.
References GameObject::boundary, camera, collision(), GEO_TEXT, meshList, modelStack, MS::PopMatrix(), GameObject::pos, Camera3::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps(), RenderGameChar(), and RenderTeleporter().
void Sp2_Scene3::RenderInstructions (GameObject x, Mesh * mesh, string text, Vector3 scale) private
Definition at line 790 of file SP2_Scene3.cpp.
References collisionXZ(), GEO_TEXT, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderText(), and MS::Translate().
Referenced by Renderfps().
void Sp2_Scene3::RenderMedic (Medic x) private
Definition at line 1176 of file SP2_Scene3.cpp.
References collision(), GEO_MEDICARM1, GEO_MEDICARM2, GEO_MEDICBODY, GEO_MEDICHEAD, GEO_TEXT, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderMesh (Mesh * mesh, bool enableLight) private
Render mesh such as basic primitive shapes and OBJs.
Parameters
mesh A pointer to the mesh that needs to be rendered
enableLight A boolean to toggle whether light has an effect on meshes or not
Definition at line 684 of file SP2_Scene3.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderBB8v2(), RenderChestBurster(), RenderChestBurster1(), Renderfps(), RenderGameObj(), RenderMedic(), RenderMeshOnScreen(), RenderNecromancer(), RenderPlatform(), RenderRocket(), RenderSir(), RenderSkybox(), RenderSuit(), and Rendertps().
void Sp2_Scene3::RenderMeshOnScreen (Mesh * mesh, Vector3 translate = Vector3(0, 0, 0), Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 1400 of file SP2_Scene3.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps(), and RenderSuit().
void Sp2_Scene3::RenderNecromancer () private
Definition at line 1287 of file SP2_Scene3.cpp.
References GEO_NECROMANCER, meshList, modelStack, Necromancer, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), AlienEnemy::wormrotating, AlienEnemy::wormtranslating, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderPingu () private
void Sp2_Scene3::RenderPlatform (Platform p, bool isRotate) private
Renders all platforms.
Parameters
p Object of the Platform class with position attribute
isRotate Boolean to decide whether platform needs to be flipped
**/
**/
*<-——>*/
*<----—>*/
Definition at line 1039 of file SP2_Scene3.cpp.
References GEO_PLATFORM, meshList, modelStack, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderRocket () private
Definition at line 1304 of file SP2_Scene3.cpp.
References GEO_ROCKET, meshList, modelStack, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), rocket, MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderSir () private
Definition at line 964 of file SP2_Scene3.cpp.
References GameObject::boundary, camera, GameChar::chat_boundary, collision(), GameChar::dialogue_index, GEO_GUIDEARMLEFT, GEO_GUIDEARMRIGHT, GEO_GUIDEBODY, GEO_GUIDEHELM, GEO_TEXT, GameChar::isPressed, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, Camera3::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Sir_, MS::Translate(), GameChar::vec_dialog, GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderSkybox () private
Definition at line 727 of file SP2_Scene3.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Renderfps(), and Rendertps().
void Sp2_Scene3::RenderSpaceVehicles (Camera3 camera) private
void Sp2_Scene3::RenderSuit () private
Rendering of the in-game suit interface and positions.
Definition at line 815 of file SP2_Scene3.cpp.
References b_collectBox1, b_collectBox2, b_collectBox3, b_isDisplayUI, b_isWorn, collision(), GEO_HELM, GEO_HELMETUI, GEO_SUIT, GEO_TEXT, GEO_TEXT2, GameChar::getHealthString(), Player::getOxygenString(), GameChar::isDead(), isFinished, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), RenderMeshOnScreen(), RenderTextOnScreen(), MS::Rotate(), rotateHelm, MS::Scale(), scaleHelm, suit, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderTeleporter (GameObject x, Mesh * mesh, string text, Vector3 scale) private
Definition at line 1425 of file SP2_Scene3.cpp.
References collisionXZ(), GEO_TEXT, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderGameObj(), RenderText(), RenderTextOnScreen(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene3::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 1315 of file SP2_Scene3.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderInstructions(), and RenderTeleporter().
void Sp2_Scene3::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 1344 of file SP2_Scene3.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderBB8v2(), Renderfps(), RenderGameChar(), RenderGameObj(), RenderMedic(), RenderSir(), RenderSuit(), and RenderTeleporter().
void Sp2_Scene3::Rendertps () private
Definition at line 1521 of file SP2_Scene3.cpp.
References GEO_AXES, meshList, RenderMesh(), and RenderSkybox().
Referenced by Render().
void Sp2_Scene3::Update (double dt) virtual
Updates health system, collision, platform, player, camera and enemy behaviours.
Implements Scene.
Definition at line 412 of file SP2_Scene3.cpp.
References b_collectBox1, b_collectBox2, b_collectBox3, b_enabletps, b_isClimb, b_isClimb2, b_isClimb3, b_isClimb4, b_isDisplayUI, SpaceVehicles::b_isInVehicle, b_isLand, b_isWorn, b_switchDir, b_tpsDebounce, BB8v2_, GameObject::boundary, box1, box2, camera, Platform::changePlatform(), GameChar::chat_update(), ChestBurster1, Buildings::climb(), collision(), collisionVec, collisionXZ(), frpc, horiDist, GameChar::isDead(), isFinished, Application::IsKeyPressed(), jerrycan, ladder, ladder2, ladder3, ladder4, landDist, Medic_, AlienEnemy::move(), Player::movementUpdate(), Necromancer, Platform::noLadderPlatform(), oldPos, Player::oxygen, Platform1, Platform10, Platform2, Platform3, Platform4, Platform5, Platform6, Platform7, Platform8, Platform9, Platform_, player, GameObject::pos, Camera3::position, GameChar::recieveHealthDamage(), GameChar::regainHealth(), rocket, BB8v2::rotateAbout(), rotateHelm, Sir::Salute(), scaleHelm, Sir_, spaceStationTp, suit, Application::switchToScene1(), tpsTimer, ChestBurster::translateWorm(), AlienEnemy::translateWorm(), Camera3::up, verticalDistance, Vector3::x, and Vector3::y.
Field Documentation
Buildings Sp2_Scene3::Arrow
Definition at line 240 of file SP2_Scene3.h.
Referenced by Init(), and Renderfps().
bool Sp2_Scene3::b_collectBox1
Definition at line 181 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), RenderSuit(), and Update().
bool Sp2_Scene3::b_collectBox2
Definition at line 182 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), RenderSuit(), and Update().
bool Sp2_Scene3::b_collectBox3
Definition at line 183 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), RenderSuit(), and Update().
bool Sp2_Scene3::b_enabletps
Definition at line 171 of file SP2_Scene3.h.
Referenced by Init(), Render(), and Update().
bool Sp2_Scene3::b_isClimb
Definition at line 175 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_isClimb2
Definition at line 176 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_isClimb3
Definition at line 177 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_isClimb4
Definition at line 178 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_isClimb6
Definition at line 179 of file SP2_Scene3.h.
Referenced by Init().
bool Sp2_Scene3::b_isDisplayUI
Definition at line 174 of file SP2_Scene3.h.
Referenced by Init(), RenderSuit(), and Update().
bool Sp2_Scene3::b_isLand
Definition at line 184 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_isWorn
Definition at line 173 of file SP2_Scene3.h.
Referenced by Init(), RenderSuit(), and Update().
bool Sp2_Scene3::b_lightEnabled
Definition at line 168 of file SP2_Scene3.h.
bool Sp2_Scene3::b_switchDir
Definition at line 180 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::b_tpsDebounce
Definition at line 172 of file SP2_Scene3.h.
Referenced by Init(), and Update().
BB8 Sp2_Scene3::BB8_
Definition at line 201 of file SP2_Scene3.h.
BB8v2 Sp2_Scene3::BB8v2_
Definition at line 202 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::box1
Definition at line 227 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::box2
Definition at line 227 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::box3
Definition at line 227 of file SP2_Scene3.h.
Referenced by Init().
Buildings Sp2_Scene3::box4
Definition at line 227 of file SP2_Scene3.h.
Referenced by Init(), and Renderfps().
Camera3 Sp2_Scene3::camera
Definition at line 164 of file SP2_Scene3.h.
Referenced by Init(), Render(), RenderBB8v2(), RenderGameObj(), RenderSir(), and Update().
CameraTPS Sp2_Scene3::camera2
Definition at line 165 of file SP2_Scene3.h.
Referenced by Render().
Buildings Sp2_Scene3::chair1
Definition at line 229 of file SP2_Scene3.h.
AlienEnemy Sp2_Scene3::ChestBurster
Definition at line 206 of file SP2_Scene3.h.
AlienEnemy Sp2_Scene3::ChestBurster1
Definition at line 208 of file SP2_Scene3.h.
Referenced by Init(), RenderChestBurster1(), and Update().
vector<GameObject*> Sp2_Scene3::collisionVec
Definition at line 246 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Buildings Sp2_Scene3::earth
Definition at line 237 of file SP2_Scene3.h.
Referenced by Init().
float Sp2_Scene3::f_rotateCube private
Definition at line 257 of file SP2_Scene3.h.
SpaceVehicles Sp2_Scene3::frpc
Definition at line 195 of file SP2_Scene3.h.
Referenced by Render(), and Update().
float Sp2_Scene3::horiDist
Definition at line 186 of file SP2_Scene3.h.
Referenced by Init(), and Update().
bool Sp2_Scene3::isFinished
Definition at line 185 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), RenderSuit(), and Update().
Buildings Sp2_Scene3::jerrycan
Definition at line 236 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::keycard1
Definition at line 230 of file SP2_Scene3.h.
Buildings Sp2_Scene3::ladder
Definition at line 231 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::ladder2
Definition at line 232 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::ladder3
Definition at line 233 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::ladder4
Definition at line 234 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
int Sp2_Scene3::landDist
Definition at line 191 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Light Sp2_Scene3::light[1] private
Definition at line 259 of file SP2_Scene3.h.
Referenced by Init(), and Renderfps().
float Sp2_Scene3::LSPEED
Definition at line 167 of file SP2_Scene3.h.
unsigned Sp2_Scene3::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 252 of file SP2_Scene3.h.
Referenced by Init().
unsigned Sp2_Scene3::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 254 of file SP2_Scene3.h.
Referenced by Init().
unsigned Sp2_Scene3::m_parameters[U_TOTAL]
Definition at line 162 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Sp2_Scene3::m_programID private
Definition at line 253 of file SP2_Scene3.h.
Referenced by Exit(), and Init().
unsigned Sp2_Scene3::m_vertexArrayID private
Definition at line 250 of file SP2_Scene3.h.
Referenced by Exit(), and Init().
unsigned Sp2_Scene3::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 251 of file SP2_Scene3.h.
Referenced by Init().
Medic Sp2_Scene3::Medic_
Definition at line 203 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Mesh* Sp2_Scene3::meshList[NUM_GEOMETRY] private
Definition at line 258 of file SP2_Scene3.h.
Referenced by Init(), RenderBB8v2(), RenderChestBurster(), RenderChestBurster1(), Renderfps(), RenderGameChar(), RenderGameObj(), RenderInstructions(), RenderMedic(), RenderNecromancer(), RenderPlatform(), RenderRocket(), RenderSir(), RenderSkybox(), RenderSuit(), RenderTeleporter(), and Rendertps().
Alien Sp2_Scene3::mike1
Definition at line 197 of file SP2_Scene3.h.
Alien Sp2_Scene3::mike2
Definition at line 197 of file SP2_Scene3.h.
Alien Sp2_Scene3::mike3
Definition at line 197 of file SP2_Scene3.h.
MS Sp2_Scene3::modelStack private
Definition at line 256 of file SP2_Scene3.h.
Referenced by RenderBB8v2(), RenderChestBurster(), RenderChestBurster1(), Renderfps(), RenderGameObj(), RenderInstructions(), RenderMedic(), RenderMesh(), RenderMeshOnScreen(), RenderNecromancer(), RenderPlatform(), RenderRocket(), RenderSir(), RenderSkybox(), RenderSuit(), RenderTeleporter(), RenderText(), and RenderTextOnScreen().
AlienEnemy Sp2_Scene3::Necromancer
Definition at line 207 of file SP2_Scene3.h.
Referenced by Init(), RenderNecromancer(), and Update().
SpaceVehicles Sp2_Scene3::np
Definition at line 194 of file SP2_Scene3.h.
Vector3 Sp2_Scene3::oldPos
Definition at line 192 of file SP2_Scene3.h.
Referenced by Update().
Pingu Sp2_Scene3::Pingu_
Definition at line 204 of file SP2_Scene3.h.
Platform Sp2_Scene3::Platform1
Definition at line 212 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Platform Sp2_Scene3::Platform10
Definition at line 221 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Platform Sp2_Scene3::Platform2
Definition at line 213 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Platform Sp2_Scene3::Platform3
Definition at line 214 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Platform Sp2_Scene3::Platform4
Definition at line 215 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Platform Sp2_Scene3::Platform5
Definition at line 216 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Platform Sp2_Scene3::Platform6
Definition at line 217 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Platform Sp2_Scene3::Platform7
Definition at line 218 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Platform Sp2_Scene3::Platform8
Definition at line 219 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Platform Sp2_Scene3::Platform9
Definition at line 220 of file SP2_Scene3.h.
Referenced by Init(), and Update().
Platform Sp2_Scene3::Platform_
Definition at line 211 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Player Sp2_Scene3::player
Definition at line 224 of file SP2_Scene3.h.
Referenced by Init(), RenderBB8v2(), Renderfps(), RenderGameChar(), RenderInstructions(), RenderMedic(), RenderSir(), RenderSkybox(), RenderSuit(), RenderTeleporter(), and Update().
MS Sp2_Scene3::projectionStack private
Definition at line 256 of file SP2_Scene3.h.
Referenced by Render(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
Quest* Sp2_Scene3::questPtr
Definition at line 244 of file SP2_Scene3.h.
Quest Sp2_Scene3::raceQuest
Definition at line 205 of file SP2_Scene3.h.
Buildings Sp2_Scene3::rocket
Definition at line 235 of file SP2_Scene3.h.
Referenced by Init(), RenderRocket(), and Update().
float Sp2_Scene3::rotateHelm
Definition at line 188 of file SP2_Scene3.h.
Referenced by Init(), RenderSuit(), and Update().
float Sp2_Scene3::scaleHelm
Definition at line 189 of file SP2_Scene3.h.
Referenced by Init(), RenderSuit(), and Update().
int Sp2_Scene3::screenHeight
Definition at line 169 of file SP2_Scene3.h.
Referenced by Init(), and Render().
int Sp2_Scene3::screenWidth
Definition at line 169 of file SP2_Scene3.h.
Referenced by Init(), and Render().
Sir Sp2_Scene3::Sir_
Definition at line 209 of file SP2_Scene3.h.
Referenced by Init(), RenderSir(), and Update().
Human Sp2_Scene3::spaceHelm
Definition at line 200 of file SP2_Scene3.h.
Referenced by Init().
Buildings Sp2_Scene3::spaceStationTp
Definition at line 238 of file SP2_Scene3.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene3::station
Definition at line 196 of file SP2_Scene3.h.
Human Sp2_Scene3::suit
Definition at line 199 of file SP2_Scene3.h.
Referenced by Init(), RenderSuit(), and Update().
Buildings Sp2_Scene3::table1
Definition at line 228 of file SP2_Scene3.h.
vector<string> Sp2_Scene3::tasklist
Definition at line 243 of file SP2_Scene3.h.
Vector3 Sp2_Scene3::tempPos
Definition at line 170 of file SP2_Scene3.h.
float Sp2_Scene3::tpsTimer
Definition at line 190 of file SP2_Scene3.h.
Referenced by Init(), and Update().
float Sp2_Scene3::verticalDistance
Definition at line 187 of file SP2_Scene3.h.
Referenced by Init(), and Update().
MS Sp2_Scene3::viewStack private
Definition at line 256 of file SP2_Scene3.h.
Referenced by Render(), Renderfps(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
MS Sp2_Scene3::viewStack2 private
Definition at line 256 of file SP2_Scene3.h.
Human Sp2_Scene3::whale
Definition at line 198 of file SP2_Scene3.h.
The documentation for this class was generated from the following files:
Computer Graphics/Source/SP2_Scene3.h
Computer Graphics/Source/SP2_Scene3.cpp