My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color, float lengthX, float lengthY)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateRing (const string &meshName, Color color, float innerRadius, unsigned numSlices)
static Mesh * GenerateSphere (const string &meshName, Color color, unsigned numSlices=36, unsigned numStack=36)
static Mesh * GenerateCylinder (const string &meshName, Color color, float topRadius, unsigned numSlice=36)
static Mesh * GenerateTorus (const string &meshName, Color color, float innerRadius, float outerRadius, unsigned numStack=36, unsigned numSlice=36)
static Mesh * GenerateHemiSphere (const string &meshName, Color color, unsigned numSlices=36, unsigned numStack=36)
static Mesh * GenerateCircleLine (const string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateHalfCircleLine (const string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 34 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 18 of file MeshBuilder.cpp.
References Vertex::col, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by LoadingScene::Init(), Sp2_Scene1::Init(), Sp2_Scene3::Init(), and Sp2_SpaceRace::Init().
Mesh * MeshBuilder::GenerateCircle (const string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 185 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCircleLine (const string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 495 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 109 of file MeshBuilder.cpp.
References Vertex::col, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Sp2_Scene1::Init().
Mesh * MeshBuilder::GenerateCylinder (const string & meshName, Color color, float topRadius, unsigned numSlice = 36) static
Definition at line 321 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHalfCircleLine (const string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 537 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHemiSphere (const string & meshName, Color color, unsigned numSlices = 36, unsigned numStack = 36) static
Definition at line 427 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 579 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by Sp2_Scene1::Init(), Sp2_Scene3::Init(), and Sp2_SpaceRace::Init().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, float lengthX, float lengthY) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 64 of file MeshBuilder.cpp.
References Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by LoadingScene::Init(), Sp2_Scene1::Init(), Sp2_Scene3::Init(), and Sp2_SpaceRace::Init().
Mesh * MeshBuilder::GenerateRing (const string & meshName, Color color, float innerRadius, unsigned numSlices) static
Definition at line 223 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const string & meshName, Color color, unsigned numSlices = 36, unsigned numStack = 36) static
Definition at line 277 of file MeshBuilder.cpp.
References Vertex::col, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), Mesh::vertexBuffer, Position::x, Position::y, and Position::z.
Referenced by Sp2_Scene1::Init(), Sp2_Scene3::Init(), and Sp2_SpaceRace::Init().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 607 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by Sp2_Scene1::Init(), Sp2_Scene3::Init(), and Sp2_SpaceRace::Init().
Mesh * MeshBuilder::GenerateTorus (const string & meshName, Color color, float innerRadius, float outerRadius, unsigned numStack = 36, unsigned numSlice = 36) static
Definition at line 384 of file MeshBuilder.cpp.
References Vertex::col, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
The documentation for this class was generated from the following files:
Computer Graphics/Source/MeshBuilder.h
Computer Graphics/Source/MeshBuilder.cpp