My Application: BB8 Class Reference
BB8 Class Reference
Class for the BB8 NPC (Inherits from GameChar) /*.
#include <BB-8.h>
Public Member Functions
BB8 ()
BB-8's default constructor implements count.
BB8 (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
BB-8's overloaded constructor with parameters implements count Sets the speed, rotating speed of BB-8's lower body as well as its' turn speed.
~BB8 ()
BB-8's default destructor decrements count.
void move (double dt)
Set BB-8 to move in circular motion using sin and cos as well as rotating while moving.
void moveCircles (double dt)
Executing move function as well as viewAngle which is for the turning speed.
void rotateAbout (double dt)
Public Member Functions inherited from GameChar
~GameChar ()
vector< string > ReadFromTxt (string link)
void chat_update (Vector3 player_pos)
bool isDead ()
smaller getHealth ()
string getHealthString ()
bool recieveHealthDamage (const int &damage)
void regainHealth (const int &healAMT=1)
void assignQuest (Quest *q)
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Data Fields
float lowerBodyRotate
float speed
float turnSpeed
Data Fields inherited from GameChar
int dialogue_index
bool b_indexDebounce
bool isPressed
vector< string > vec_dialog
bool b_dialogueEnd
int chat_boundary
Quest * quest
Data Fields inherited from GameObject
string name
int boundary
Vector3 pos
float viewAngle
Static Public Attributes
static size_t bb8_count = 0
Static Public Attributes inherited from GameChar
static size_t GC_count = 0
Additional Inherited Members
Protected Member Functions inherited from GameChar
GameChar ()
GameChar (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0), smaller init_Health=0)
Protected Member Functions inherited from GameObject
GameObject ()
GameObject (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
Detailed Description
Class for the BB8 NPC (Inherits from GameChar) /*.
Class BB8:
Definition at line 25 of file BB-8.h.
Constructor & Destructor Documentation
BB8::BB8 ()
BB-8's default constructor implements count.
Definition at line 24 of file BB-8.cpp.
References bb8_count.
BB8::BB8 (string object_name, int boundary, float viewAngle = 0, Vector3 pos = Vector3(0, 0, 0))
BB-8's overloaded constructor with parameters implements count Sets the speed, rotating speed of BB-8's lower body as well as its' turn speed.
Parameters
string object_name, int boundary, float viewAngle, Vector3 pos
Definition at line 37 of file BB-8.cpp.
References bb8_count, lowerBodyRotate, speed, and turnSpeed.
BB8::~BB8 ()
BB-8's default destructor decrements count.
Definition at line 50 of file BB-8.cpp.
References bb8_count.
Member Function Documentation
void BB8::move (double dt)
Set BB-8 to move in circular motion using sin and cos as well as rotating while moving.
Parameters
double dt
Definition at line 62 of file BB-8.cpp.
References Math::DegreeToRadian(), lowerBodyRotate, GameObject::pos, speed, GameObject::viewAngle, Vector3::x, and Vector3::z.
Referenced by moveCircles().
void BB8::moveCircles (double dt)
Executing move function as well as viewAngle which is for the turning speed.
Parameters
double dt
Definition at line 76 of file BB-8.cpp.
References move(), turnSpeed, and GameObject::viewAngle.
Referenced by Sp2_Scene1::Update().
void BB8::rotateAbout (double dt)
Field Documentation
size_t BB8::bb8_count = 0 static
Definition at line 31 of file BB-8.h.
Referenced by BB8(), and ~BB8().
float BB8::lowerBodyRotate
Definition at line 32 of file BB-8.h.
Referenced by BB8(), and move().
float BB8::speed
Definition at line 33 of file BB-8.h.
Referenced by BB8(), and move().
float BB8::turnSpeed
Definition at line 34 of file BB-8.h.
Referenced by BB8(), and moveCircles().
The documentation for this class was generated from the following files:
Computer Graphics/Source/BB-8.h
Computer Graphics/Source/BB-8.cpp