My Application: Platform Class Reference
Platform Class Reference
Class for Platform (Inheriting from GameChar) /*.
#include <Platform.h>
Public Member Functions
Platform ()
Platform's default constructor implements count.
Platform (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
Platform's overloaded constructor with parameters implements count.
~Platform ()
Platform's default destructor decrements count.
void move (double dt)
Sets the movement of the Platform (To be edited)
void moveCircles (double dt)
Executing move function as well as rotation while moving.
void rotateAbout (double dt)
ViewAngle is for turning speed, rotating at its own position without moving around.
void changePlatform (bool &isClimb, Platform &p, Player &player)
void noLadderPlatform (Platform &p, Player &player)
Public Member Functions inherited from GameChar
~GameChar ()
vector< string > ReadFromTxt (string link)
void chat_update (Vector3 player_pos)
bool isDead ()
smaller getHealth ()
string getHealthString ()
bool recieveHealthDamage (const int &damage)
void regainHealth (const int &healAMT=1)
void assignQuest (Quest *q)
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Data Fields
float lowerBodyRotate
float speed
float turnSpeed
Data Fields inherited from GameChar
int dialogue_index
bool b_indexDebounce
bool isPressed
vector< string > vec_dialog
bool b_dialogueEnd
int chat_boundary
Quest * quest
Data Fields inherited from GameObject
string name
int boundary
Vector3 pos
float viewAngle
Static Public Attributes
static size_t Platform_count = 0
Static Public Attributes inherited from GameChar
static size_t GC_count = 0
Additional Inherited Members
Protected Member Functions inherited from GameChar
GameChar ()
GameChar (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0), smaller init_Health=0)
Protected Member Functions inherited from GameObject
GameObject ()
GameObject (string object_name, int boundary, float viewAngle=0, Vector3 pos=Vector3(0, 0, 0))
Detailed Description
Class for Platform (Inheriting from GameChar) /*.
Class Platform:
Definition at line 26 of file Platform.h.
Constructor & Destructor Documentation
Platform::Platform ()
Platform's default constructor implements count.
Definition at line 24 of file Platform.cpp.
References Platform_count.
Platform::Platform (string object_name, int boundary, float viewAngle = 0, Vector3 pos = Vector3(0, 0, 0))
Platform's overloaded constructor with parameters implements count.
Parameters
string object_name, int boundary, float viewAngle, Vector3 pos
Definition at line 36 of file Platform.cpp.
References lowerBodyRotate, Platform_count, speed, and turnSpeed.
Platform::~Platform ()
Platform's default destructor decrements count.
Definition at line 49 of file Platform.cpp.
References Platform_count.
Member Function Documentation
void Platform::changePlatform (bool & isClimb, Platform & p, Player & player)
Definition at line 94 of file Platform.cpp.
References GameObject::boundary, collision(), GameObject::pos, and Vector3::y.
Referenced by Sp2_Scene3::Update().
void Platform::move (double dt)
Sets the movement of the Platform (To be edited)
Parameters
double dt
Definition at line 61 of file Platform.cpp.
References Math::DegreeToRadian(), lowerBodyRotate, GameObject::pos, speed, GameObject::viewAngle, Vector3::x, and Vector3::z.
Referenced by moveCircles().
void Platform::moveCircles (double dt)
Executing move function as well as rotation while moving.
Parameters
double dt
Definition at line 75 of file Platform.cpp.
References move(), turnSpeed, and GameObject::viewAngle.
void Platform::noLadderPlatform (Platform & p, Player & player)
Definition at line 107 of file Platform.cpp.
References GameObject::boundary, collision(), and GameObject::pos.
Referenced by Sp2_Scene3::Update().
void Platform::rotateAbout (double dt)
ViewAngle is for turning speed, rotating at its own position without moving around.
Parameters
double dt
Definition at line 88 of file Platform.cpp.
References turnSpeed, and GameObject::viewAngle.
Field Documentation
float Platform::lowerBodyRotate
Definition at line 33 of file Platform.h.
Referenced by move(), and Platform().
size_t Platform::Platform_count = 0 static
Definition at line 32 of file Platform.h.
Referenced by Platform(), and ~Platform().
float Platform::speed
Definition at line 34 of file Platform.h.
Referenced by move(), and Platform().
float Platform::turnSpeed
Definition at line 35 of file Platform.h.
Referenced by moveCircles(), Platform(), and rotateAbout().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Platform.h
Computer Graphics/Source/Platform.cpp