My Application: Sp2_Scene1 Class Reference
Sp2_Scene1 Class Reference
Class for Scene 1 of the game inheriting from Scene /*.
#include <Sp2_Scene1.h>
Public Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, GEO_LEFT,
GEO_RIGHT, GEO_TOP, GEO_BOTTOM, GEO_FRONT,
GEO_BACK, GEO_TEXT, GEO_TEXT2, GEO_TEXTBACKGROUND,
GEO_FOURTH, GEO_NPCLEPUSMAG, GEO_STATION, GEO_SNIPERRIFLE,
GEO_DART, GEO_CROSSHAIR, GEO_DOOR, GEO_MIKE,
GEO_NPC3, GEO_FLIGHTUI, GEO_HELMETUI, GEO_BB8H,
GEO_BB8B, GEO_PINGU, GEO_ALIEN, GEO_BOX,
GEO_TABLE, GEO_CHAIR, GEO_KEYCARD, GEO_TELEPORTER,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Public Member Functions
Sp2_Scene1 ()
~Sp2_Scene1 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
unsigned m_parameters [U_TOTAL]
Camera3 camera
CameraTPS camera2
float LSPEED
bool b_lightEnabled
int screenWidth
int screenHeight
Vector3 tempPos
bool b_enabletps
bool b_tpsDebounce
bool b_isWorn
bool b_isDisplayUI
float rotateHelm
float scaleHelm
float tpsTimer
bool gameComplete
SpaceVehicles np
SpaceVehicles frpc
Buildings station
Alien mike1
Alien mike2
Alien mike3
Human whale
Buildings door
BB8 BB8_
Pingu Pingu_
Quest raceQuest
Player player
Buildings box1
Buildings box2
Buildings box3
Buildings box4
Buildings table1
Buildings chair1
Buildings keycard1
Buildings scene3Tp
Buildings raceTp
vector< string > tasklist
Quest * questPtr
vector< GameObject * > collisionVec
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSkybox ()
void RenderSpaceVehicles (Camera3 camera)
void RenderBB8 (BB8 x)
void RenderGameObj (GameObject x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1), smaller axis=0)
void RenderGameChar (GameChar x, Mesh *mesh, bool enableLight=true, bool hasInteraction=false, Vector3 scale=Vector3(1, 1, 1))
void RenderTeleporter (GameObject x, Mesh *mesh, string text, Vector3 scale)
void Renderfps ()
void Rendertps ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderMeshOnScreen (Mesh *mesh, Vector3 translate=Vector3(0, 0, 0), Vector3 scale=Vector3(1, 1, 1), Vector3 rotate=Vector3(0, 0, 0))
Private Attributes
unsigned m_vertexArrayID
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_indexBuffer [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
MS viewStack2
float f_rotateCube
Mesh * meshList [NUM_GEOMETRY]
Light light [1]
Detailed Description
Class for Scene 1 of the game inheriting from Scene /*.
Class Sp2_Scene1:
Definition at line 47 of file Sp2_Scene1.h.
Member Enumeration Documentation
enum Sp2_Scene1::GEOMETRY_TYPE
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_TEXT
GEO_TEXT2
GEO_TEXTBACKGROUND
GEO_FOURTH
GEO_NPCLEPUSMAG
GEO_STATION
GEO_SNIPERRIFLE
GEO_DART
GEO_CROSSHAIR
GEO_DOOR
GEO_MIKE
GEO_NPC3
GEO_FLIGHTUI
GEO_HELMETUI
GEO_BB8H
GEO_BB8B
GEO_PINGU
GEO_ALIEN
GEO_BOX
GEO_TABLE
GEO_CHAIR
GEO_KEYCARD
GEO_TELEPORTER
NUM_GEOMETRY
Definition at line 58 of file Sp2_Scene1.h.
enum Sp2_Scene1::UNIFORM_TYPE
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 107 of file Sp2_Scene1.h.
Constructor & Destructor Documentation
Sp2_Scene1::Sp2_Scene1 ()
Definition at line 16 of file Sp2_Scene1.cpp.
Sp2_Scene1::~Sp2_Scene1 ()
Definition at line 20 of file Sp2_Scene1.cpp.
References player, and Player::questList.
Member Function Documentation
void Sp2_Scene1::Exit () virtual
Implements Scene.
Definition at line 790 of file Sp2_Scene1.cpp.
References m_programID, and m_vertexArrayID.
void Sp2_Scene1::Init () virtual
Implements Scene.
Definition at line 25 of file Sp2_Scene1.cpp.
References b_enabletps, b_isDisplayUI, b_isWorn, b_tpsDebounce, BB8_, box1, box2, box3, box4, camera, chair1, collisionVec, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), door, Light::exponent, gameComplete, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ALIEN, GEO_AXES, GEO_BACK, GEO_BB8B, GEO_BB8H, GEO_BOTTOM, GEO_BOX, GEO_CHAIR, GEO_DART, GEO_DOOR, GEO_FOURTH, GEO_FRONT, GEO_HELMETUI, GEO_LEFT, GEO_LIGHTBALL, GEO_MIKE, GEO_NPCLEPUSMAG, GEO_QUAD, GEO_RIGHT, GEO_SNIPERRIFLE, GEO_STATION, GEO_TABLE, GEO_TELEPORTER, GEO_TEXT, GEO_TEXT2, GEO_TEXTBACKGROUND, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, LoadShaders(), LoadTGA(), m_colorBuffer, m_indexBuffer, m_parameters, m_programID, m_vertexArrayID, m_vertexBuffer, m_window, meshList, mike1, mike2, mike3, NUM_GEOMETRY, player, Light::position, Light::power, raceTp, GameChar::ReadFromTxt(), rotateHelm, scaleHelm, scene3Tp, screenHeight, screenWidth, Position::Set(), Vector3::Set(), Color::Set(), Player::setQuest(), Light::spotDirection, station, table1, Mesh::textureID, tpsTimer, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, and whale.
void Sp2_Scene1::Render () virtual
Implements Scene.
Definition at line 741 of file Sp2_Scene1.cpp.
References b_enabletps, camera, camera2, MS::LoadIdentity(), MS::LoadMatrix(), MS::LookAt(), Camera3::position, Camera::position, projectionStack, Renderfps(), Rendertps(), screenHeight, screenWidth, Mtx44::SetToPerspective(), Camera3::target, Camera::target, Camera3::up, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Sp2_Scene1::RenderBB8 (BB8 x) private
Definition at line 537 of file Sp2_Scene1.cpp.
References GEO_BB8B, GEO_BB8H, meshList, modelStack, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene1::Renderfps () private
Definition at line 672 of file Sp2_Scene1.cpp.
References BB8_, box1, box2, box3, box4, chair1, door, gameComplete, GEO_ALIEN, GEO_AXES, GEO_BOX, GEO_CHAIR, GEO_DOOR, GEO_LIGHTBALL, GEO_MIKE, GEO_NPCLEPUSMAG, GEO_STATION, GEO_TABLE, GEO_TELEPORTER, GEO_TEXT, light, m_parameters, meshList, mike1, mike2, mike3, modelStack, MS::PopMatrix(), GameObject::pos, Light::position, MS::PushMatrix(), raceTp, RenderBB8(), RenderGameChar(), RenderGameObj(), RenderMesh(), RenderSkybox(), RenderTeleporter(), RenderText(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), scene3Tp, station, table1, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, viewStack, whale, Vector3::x, Position::y, Vector3::y, Vector3::z, and Position::z.
Referenced by Render().
void Sp2_Scene1::RenderGameChar (GameChar x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1)) private
Definition at line 519 of file Sp2_Scene1.cpp.
References GameObject::boundary, GameChar::chat_boundary, collision(), GameChar::dialogue_index, GEO_TEXT, GameChar::isPressed, meshList, player, GameObject::pos, RenderGameObj(), RenderTextOnScreen(), and GameChar::vec_dialog.
Referenced by Renderfps().
void Sp2_Scene1::RenderGameObj (GameObject x, Mesh * mesh, bool enableLight = true, bool hasInteraction = false, Vector3 scale = Vector3(1, 1, 1), smaller axis = 0) private
Definition at line 477 of file Sp2_Scene1.cpp.
References GameObject::boundary, camera, collision(), GEO_TEXT, meshList, modelStack, MS::PopMatrix(), GameObject::pos, Camera3::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), MS::Translate(), GameObject::viewAngle, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps(), RenderGameChar(), and RenderTeleporter().
void Sp2_Scene1::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 372 of file Sp2_Scene1.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderBB8(), Renderfps(), RenderGameObj(), RenderMeshOnScreen(), RenderSkybox(), and Rendertps().
void Sp2_Scene1::RenderMeshOnScreen (Mesh * mesh, Vector3 translate = Vector3(0, 0, 0), Vector3 scale = Vector3(1, 1, 1), Vector3 rotate = Vector3(0, 0, 0)) private
Definition at line 647 of file Sp2_Scene1.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Sp2_Scene1::RenderSkybox () private
Definition at line 415 of file Sp2_Scene1.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Renderfps(), and Rendertps().
void Sp2_Scene1::RenderSpaceVehicles (Camera3 camera) private
void Sp2_Scene1::RenderTeleporter (GameObject x, Mesh * mesh, string text, Vector3 scale) private
Definition at line 500 of file Sp2_Scene1.cpp.
References collisionXZ(), GEO_TEXT, meshList, modelStack, player, MS::PopMatrix(), GameObject::pos, MS::PushMatrix(), RenderGameObj(), RenderText(), RenderTextOnScreen(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Renderfps().
void Sp2_Scene1::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 563 of file Sp2_Scene1.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Renderfps(), and RenderTeleporter().
void Sp2_Scene1::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 592 of file Sp2_Scene1.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Renderfps(), RenderGameChar(), RenderGameObj(), and RenderTeleporter().
void Sp2_Scene1::Rendertps () private
Definition at line 735 of file Sp2_Scene1.cpp.
References GEO_AXES, meshList, RenderMesh(), and RenderSkybox().
Referenced by Render().
void Sp2_Scene1::Update (double dt) virtual
Implements Scene.
Definition at line 273 of file Sp2_Scene1.cpp.
References GameChar::b_dialogueEnd, b_enabletps, b_tpsDebounce, BB8_, camera, GameChar::chat_update(), collisionVec, collisionXZ(), Player::completedMainQuest(), door, gameComplete, Application::IsKeyPressed(), mike2, mike3, BB8::moveCircles(), Player::movementUpdate(), player, GameObject::pos, Player::questList, raceTp, scene3Tp, Application::switchToScene2(), Application::switchToScene3(), tpsTimer, whale, and Vector3::x.
Field Documentation
bool Sp2_Scene1::b_enabletps
Definition at line 145 of file Sp2_Scene1.h.
Referenced by Init(), Render(), and Update().
bool Sp2_Scene1::b_isDisplayUI
Definition at line 148 of file Sp2_Scene1.h.
Referenced by Init().
bool Sp2_Scene1::b_isWorn
Definition at line 147 of file Sp2_Scene1.h.
Referenced by Init().
bool Sp2_Scene1::b_lightEnabled
Definition at line 142 of file Sp2_Scene1.h.
bool Sp2_Scene1::b_tpsDebounce
Definition at line 146 of file Sp2_Scene1.h.
Referenced by Init(), and Update().
BB8 Sp2_Scene1::BB8_
Definition at line 160 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene1::box1
Definition at line 168 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Buildings Sp2_Scene1::box2
Definition at line 168 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Buildings Sp2_Scene1::box3
Definition at line 168 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Buildings Sp2_Scene1::box4
Definition at line 168 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Camera3 Sp2_Scene1::camera
Definition at line 138 of file Sp2_Scene1.h.
Referenced by Init(), Render(), RenderGameObj(), and Update().
CameraTPS Sp2_Scene1::camera2
Definition at line 139 of file Sp2_Scene1.h.
Referenced by Render().
Buildings Sp2_Scene1::chair1
Definition at line 170 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
vector<GameObject*> Sp2_Scene1::collisionVec
Definition at line 178 of file Sp2_Scene1.h.
Referenced by Init(), and Update().
Buildings Sp2_Scene1::door
Definition at line 159 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
float Sp2_Scene1::f_rotateCube private
Definition at line 189 of file Sp2_Scene1.h.
SpaceVehicles Sp2_Scene1::frpc
Definition at line 155 of file Sp2_Scene1.h.
bool Sp2_Scene1::gameComplete
Definition at line 152 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
Buildings Sp2_Scene1::keycard1
Definition at line 171 of file Sp2_Scene1.h.
Light Sp2_Scene1::light[1] private
Definition at line 191 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
float Sp2_Scene1::LSPEED
Definition at line 141 of file Sp2_Scene1.h.
unsigned Sp2_Scene1::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 184 of file Sp2_Scene1.h.
Referenced by Init().
unsigned Sp2_Scene1::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 186 of file Sp2_Scene1.h.
Referenced by Init().
unsigned Sp2_Scene1::m_parameters[U_TOTAL]
Definition at line 136 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Sp2_Scene1::m_programID private
Definition at line 185 of file Sp2_Scene1.h.
Referenced by Exit(), and Init().
unsigned Sp2_Scene1::m_vertexArrayID private
Definition at line 182 of file Sp2_Scene1.h.
Referenced by Exit(), and Init().
unsigned Sp2_Scene1::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 183 of file Sp2_Scene1.h.
Referenced by Init().
Mesh* Sp2_Scene1::meshList[NUM_GEOMETRY] private
Definition at line 190 of file Sp2_Scene1.h.
Referenced by Init(), RenderBB8(), Renderfps(), RenderGameChar(), RenderGameObj(), RenderSkybox(), RenderTeleporter(), and Rendertps().
Alien Sp2_Scene1::mike1
Definition at line 157 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Alien Sp2_Scene1::mike2
Definition at line 157 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
Alien Sp2_Scene1::mike3
Definition at line 157 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
MS Sp2_Scene1::modelStack private
Definition at line 188 of file Sp2_Scene1.h.
Referenced by RenderBB8(), Renderfps(), RenderGameObj(), RenderMesh(), RenderMeshOnScreen(), RenderSkybox(), RenderTeleporter(), RenderText(), and RenderTextOnScreen().
SpaceVehicles Sp2_Scene1::np
Definition at line 154 of file Sp2_Scene1.h.
Pingu Sp2_Scene1::Pingu_
Definition at line 161 of file Sp2_Scene1.h.
Player Sp2_Scene1::player
Definition at line 165 of file Sp2_Scene1.h.
Referenced by Init(), RenderGameChar(), RenderTeleporter(), Update(), and ~Sp2_Scene1().
MS Sp2_Scene1::projectionStack private
Definition at line 188 of file Sp2_Scene1.h.
Referenced by Render(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
Quest* Sp2_Scene1::questPtr
Definition at line 176 of file Sp2_Scene1.h.
Quest Sp2_Scene1::raceQuest
Definition at line 162 of file Sp2_Scene1.h.
Buildings Sp2_Scene1::raceTp
Definition at line 172 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
float Sp2_Scene1::rotateHelm
Definition at line 149 of file Sp2_Scene1.h.
Referenced by Init().
float Sp2_Scene1::scaleHelm
Definition at line 150 of file Sp2_Scene1.h.
Referenced by Init().
Buildings Sp2_Scene1::scene3Tp
Definition at line 172 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
int Sp2_Scene1::screenHeight
Definition at line 143 of file Sp2_Scene1.h.
Referenced by Init(), and Render().
int Sp2_Scene1::screenWidth
Definition at line 143 of file Sp2_Scene1.h.
Referenced by Init(), and Render().
Buildings Sp2_Scene1::station
Definition at line 156 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
Buildings Sp2_Scene1::table1
Definition at line 169 of file Sp2_Scene1.h.
Referenced by Init(), and Renderfps().
vector<string> Sp2_Scene1::tasklist
Definition at line 175 of file Sp2_Scene1.h.
Vector3 Sp2_Scene1::tempPos
Definition at line 144 of file Sp2_Scene1.h.
float Sp2_Scene1::tpsTimer
Definition at line 151 of file Sp2_Scene1.h.
Referenced by Init(), and Update().
MS Sp2_Scene1::viewStack private
Definition at line 188 of file Sp2_Scene1.h.
Referenced by Render(), Renderfps(), RenderMesh(), RenderMeshOnScreen(), RenderText(), and RenderTextOnScreen().
MS Sp2_Scene1::viewStack2 private
Definition at line 188 of file Sp2_Scene1.h.
Human Sp2_Scene1::whale
Definition at line 158 of file Sp2_Scene1.h.
Referenced by Init(), Renderfps(), and Update().
The documentation for this class was generated from the following files:
Computer Graphics/Source/Sp2_Scene1.h
Computer Graphics/Source/Sp2_Scene1.cpp