My Application: Computer Graphics/Source/Collision.h File Reference
Collision.h File Reference
Class to define the overall collision for the scenes.
#include "GameObject.h"
Functions
bool collision (GameObject x, GameObject y)
bool collision (GameObject x, vector< GameObject > y)
bool collision (GameObject x, Vector3 y, int boundary)
bool collision (Vector3 x, Vector3 y, int boundary)
bool collision (Vector3 x, vector< GameObject * > y, float boundary)
bool collisionXZ (Vector3 x, GameObject y)
vector< GameObject > collisionElimination (GameObject x, vector< GameObject > y)
Detailed Description
Class to define the overall collision for the scenes.
Author
Lee Jian Lin
Email: 150580X.nyp.edu.sg
Admin Number: 150580X
School: Nanyang Polytechnic (School of Interactive and Digital Media)
Diploma: Game Development and Technology
Class: GD1503
Mobile Number: 9755 2038
Definition in file Collision.h.
Function Documentation
bool collision (GameObject x, GameObject y)
Definition at line 3 of file Collision.cpp.
References GameObject::boundary, GameObject::pos, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Platform::changePlatform(), GameChar::chat_update(), Buildings::climb(), collision(), collisionElimination(), SpaceVehicles::enterVehicleUpdate(), Player::movementUpdate(), Platform::noLadderPlatform(), Sp2_Scene3::RenderBB8v2(), Sp2_Scene1::RenderGameChar(), Sp2_SpaceRace::RenderGameChar(), Sp2_Scene3::RenderGameChar(), Sp2_Scene1::RenderGameObj(), Sp2_SpaceRace::RenderGameObj(), Sp2_Scene3::RenderGameObj(), Sp2_Scene3::RenderMedic(), Sp2_Scene3::RenderSir(), Sp2_Scene3::RenderSuit(), Sp2_Scene3::Update(), SpaceVehicles::updateCPUVehicle(), SpaceVehicles::updateVehicle(), and SpaceVehicles::updateVehicle2().
bool collision (GameObject x, vector< GameObject > y)
Definition at line 94 of file Collision.cpp.
References collision().
bool collision (GameObject x, Vector3 y, int boundary)
Definition at line 37 of file Collision.cpp.
References GameObject::boundary, collision(), and GameObject::pos.
bool collision (Vector3 x, Vector3 y, int boundary)
Definition at line 68 of file Collision.cpp.
References Vector3::x, Vector3::y, and Vector3::z.
bool collision (Vector3 x, vector< GameObject * > y, float boundary)
Definition at line 106 of file Collision.cpp.
References collision().
vector<GameObject> collisionElimination (GameObject x, vector< GameObject > y)
Definition at line 121 of file Collision.cpp.
References GameObject::boundary, collision(), GameObject::pos, and Vector3::y.
bool collisionXZ (Vector3 x, GameObject y)
Definition at line 42 of file Collision.cpp.
References GameObject::boundary, GameObject::pos, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Sp2_Scene3::RenderInstructions(), Sp2_Scene1::RenderTeleporter(), Sp2_SpaceRace::RenderTeleporter(), Sp2_Scene3::RenderTeleporter(), Sp2_Scene1::Update(), Sp2_Scene3::Update(), and Sp2_SpaceRace::Update().