My Application: Computer Graphics/irrKlang/plugins/ikpMP3/decoder/internal.h File Reference
internal.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <stddef.h>
#include "mpaudec.h"
#include <inttypes.h>
#include <assert.h>
Data Structures
struct GetBitContext
struct VLC
Macros
#define M_PI 3.14159265358979323846
#define NDEBUG
#define VLC_TYPE int16_t
Typedefs
typedef struct GetBitContext GetBitContext
typedef struct VLC VLC
Functions
int get_bits_count (const GetBitContext *s)
unsigned int get_bits (GetBitContext *s, int n)
unsigned int show_bits (const GetBitContext *s, int n)
void skip_bits (GetBitContext *s, int n)
void init_get_bits (GetBitContext *s, const uint8_t *buffer, int buffer_size)
init GetBitContext.
int init_vlc (VLC *vlc, int nb_bits, int nb_codes, const void *bits, int bits_wrap, int bits_size, const void *codes, int codes_wrap, int codes_size)
void free_vlc (VLC *vlc)
int get_vlc (GetBitContext *s, const VLC *vlc)
Macro Definition Documentation
#define M_PI 3.14159265358979323846
Definition at line 20 of file internal.h.
Referenced by mpaudec_init().
#define NDEBUG
Definition at line 52 of file internal.h.
#define VLC_TYPE int16_t
Definition at line 66 of file internal.h.
Referenced by alloc_table(), and build_table().
Typedef Documentation
typedef struct GetBitContext GetBitContext
typedef struct VLC VLC
Function Documentation
void free_vlc (VLC * vlc)
Definition at line 248 of file bits.c.
References VLC::table.
unsigned int get_bits (GetBitContext * s, int n)
Definition at line 63 of file bits.c.
References show_bits(), and skip_bits().
Referenced by get_bitsz(), huffman_decode(), mp_decode_frame(), mp_decode_layer1(), mp_decode_layer2(), and mp_decode_layer3().
int get_bits_count (const GetBitContext * s)
Definition at line 70 of file bits.c.
References GetBitContext::index.
Referenced by huffman_decode(), mp_decode_layer3(), and seek_to_maindata().
int get_vlc (GetBitContext * s, const VLC * vlc)
Definition at line 253 of file bits.c.
References VLC::bits, show_bits(), skip_bits(), and VLC::table.
Referenced by huffman_decode().
void init_get_bits (GetBitContext * s, const uint8_t * buffer, int bit_size)
init GetBitContext.
Parameters
buffer bitstream buffer
bit_size the size of the buffer in bits
Definition at line 30 of file bits.c.
References GetBitContext::buffer, GetBitContext::index, and GetBitContext::size_in_bits.
Referenced by mp_decode_frame(), and seek_to_maindata().
int init_vlc (VLC * vlc, int nb_bits, int nb_codes, const void * bits, int bits_wrap, int bits_size, const void * codes, int codes_wrap, int codes_size)
Definition at line 225 of file bits.c.
References VLC::bits, build_table(), VLC::table, VLC::table_allocated, and VLC::table_size.
Referenced by mpaudec_init().
unsigned int show_bits (const GetBitContext * s, int n)
Definition at line 38 of file bits.c.
References GetBitContext::buffer, GetBitContext::index, and GetBitContext::size_in_bits.
Referenced by get_bits(), and get_vlc().
void skip_bits (GetBitContext * s, int n)
Definition at line 58 of file bits.c.
References GetBitContext::index.
Referenced by get_bits(), get_vlc(), and mp_decode_layer3().