My Application: Computer Graphics/Source/Map.h File Reference
Map.h File Reference
Class to define the maps.
#include <string>
#include <fstream>
#include <iostream>
#include "Vector3.h"
Data Structures
struct sMap
Struct for Map /*.
Typedefs
typedef struct sMap MAP
Struct for Map /*.
typedef struct sMap * PMAP
Functions
PMAP load_map (string filename)
Vector3 indexToVector (int index)
int vectorToIndex (Vector3 pos)
int toIndex (int row, int col)
Detailed Description
Class to define the maps.
Author
Lee Jian Lin
Email: 150580X.nyp.edu.sg
Admin Number: 150580X
School: Nanyang Polytechnic (School of Interactive and Digital Media)
Diploma: Game Development and Technology
Class: GD1503
Mobile Number: 9755 2038
Definition in file Map.h.
Typedef Documentation
typedef struct sMap MAP
Struct for Map /*.
Struct sMap:
typedef struct sMap* PMAP
Function Documentation
Vector3 indexToVector (int index)
Definition at line 46 of file Map.cpp.
Referenced by SpaceVehicles::distanceFromCheckpoint(), Sp2_SpaceRace::Init(), Sp2_SpaceRace::Renderfps(), Sp2_SpaceRace::Rendertps(), Sp2_SpaceRace::Update(), SpaceVehicles::updateCPUVehicle(), SpaceVehicles::updateVehicle(), and SpaceVehicles::updateVehicle2().
PMAP load_map (string filename)
Definition at line 3 of file Map.cpp.
References sMap::data.
Referenced by Sp2_SpaceRace::Init().
int toIndex (int row, int col)
Definition at line 62 of file Map.cpp.
Referenced by Sp2_SpaceRace::Init(), and Sp2_SpaceRace::Update().
int vectorToIndex (Vector3 pos)
Definition at line 55 of file Map.cpp.
References Vector3::x, and Vector3::z.
Referenced by Player::movementUpdate(), SpaceVehicles::updateCPUVehicle(), SpaceVehicles::updateVehicle(), and SpaceVehicles::updateVehicle2().