My Application: Vector2 Struct Reference
Vector2 Struct Reference
#include <Vector2.h>
Public Member Functions
Vector2 (float a=0, float b=0)
Vector2 (const Vector2 &rhs)
void Set (float a, float b)
Vector2 operator+ (const Vector2 &rhs) const
Vector2 operator- (const Vector2 &rhs) const
Vector2 operator- (void) const
Vector2 operator* (float scalar) const
float Length (void) const
float Dot (const Vector2 &rhs) const
Vector2 Normalized (void)
Detailed Description
Definition at line 4 of file Vector2.h.
Constructor & Destructor Documentation
Vector2::Vector2 (float a = 0, float b = 0)
Definition at line 3 of file Vector2.cpp.
Referenced by Normalized(), operator*(), operator+(), and operator-().
Vector2::Vector2 (const Vector2 & rhs)
Definition at line 7 of file Vector2.cpp.
Member Function Documentation
float Vector2::Dot (const Vector2 & rhs) const
Definition at line 40 of file Vector2.cpp.
float Vector2::Length (void) const
Definition at line 35 of file Vector2.cpp.
Vector2 Vector2::Normalized (void)
Definition at line 45 of file Vector2.cpp.
References Vector2().
Vector2 Vector2::operator* (float scalar) const
Definition at line 30 of file Vector2.cpp.
References Vector2().
Vector2 Vector2::operator+ (const Vector2 & rhs) const
Definition at line 15 of file Vector2.cpp.
References Vector2().
Vector2 Vector2::operator- (const Vector2 & rhs) const
Definition at line 20 of file Vector2.cpp.
References Vector2().
Vector2 Vector2::operator- (void) const
Definition at line 25 of file Vector2.cpp.
References Vector2().
void Vector2::Set (float a, float b)
Definition at line 11 of file Vector2.cpp.
The documentation for this struct was generated from the following files:
Common Library/Source/Vector2.h
Common Library/Source/Vector2.cpp